/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SubscriptionsCollectionApi.h
 *
 * 
 */

#ifndef SubscriptionsCollectionApi_H_
#define SubscriptionsCollectionApi_H_


#include "ApiBase.h"

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include <optional>
#include <utility>

#include "CreateEventSubscription.h"
#include "CreatedEventSubscription.h"
#include "ProblemDetails.h"
#include "RedirectResponse.h"
#include <string>

namespace org::openapitools::server::api
{

class  SubscriptionsCollectionApi : public ApiBase {
public:
    explicit SubscriptionsCollectionApi(const std::shared_ptr<Pistache::Rest::Router>& rtr);
    virtual ~SubscriptionsCollectionApi() = default;
    void init();

    static const std::string base;

private:
    void setupRoutes();

    void create_subscription_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void subscriptions_collection_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    /// <summary>
    /// Helper function to handle unexpected Exceptions during Parameter parsing and validation.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(const std::exception& ex) const noexcept;

    /// <summary>
    /// Helper function to handle unexpected Exceptions during processing of the request in handler functions.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(const std::exception& ex) const noexcept;

    /// <summary>
    /// Nupf_EventExposure Subscribe service Operation
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="createEventSubscription"></param>
    virtual void create_subscription(const org::openapitools::server::model::CreateEventSubscription &createEventSubscription, Pistache::Http::ResponseWriter &response) = 0;

};

} // namespace org::openapitools::server::api

#endif /* SubscriptionsCollectionApi_H_ */

