/**
* UPF GET Private UE IP address Service
* Nupf_GetPrivateUEIPaddr Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.0.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "UEIPInfoGetApi.h"
#include "Helpers.h"

namespace org::openapitools::server::api
{

using namespace org::openapitools::server::helpers;
using namespace org::openapitools::server::model;

const std::string UEIPInfoGetApi::base = "/nupf-gueip/v1";

UEIPInfoGetApi::UEIPInfoGetApi(const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : ApiBase(rtr)
{
}

void UEIPInfoGetApi::init() {
    setupRoutes();
}

void UEIPInfoGetApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Get(*router, base + "/ue-ip-info", Routes::bind(&UEIPInfoGetApi::search_ue_ip_info_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&UEIPInfoGetApi::ueip_info_get_api_default_handler, this));
}

std::pair<Pistache::Http::Code, std::string> UEIPInfoGetApi::handleParsingException(const std::exception& ex) const noexcept
{
    try {
        throw;
    } catch (nlohmann::detail::exception &e) {
        return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
    } catch (org::openapitools::server::helpers::ValidationException &e) {
        return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
    } catch (std::exception &e) {
        return std::make_pair(Pistache::Http::Code::Internal_Server_Error, e.what());
    }
}

std::pair<Pistache::Http::Code, std::string> UEIPInfoGetApi::handleOperationException(const std::exception& ex) const noexcept
{
    return std::make_pair(Pistache::Http::Code::Internal_Server_Error, ex.what());
}

void UEIPInfoGetApi::search_ue_ip_info_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    try {


    // Getting the query params
    auto snssaiQuery = request.query().get("snssai");
    std::optional<Snssai> snssai;
    if(snssaiQuery.has_value()){
        Snssai valueQuery_instance;
        if(fromStringValue(snssaiQuery.value(), valueQuery_instance)){
            snssai = valueQuery_instance;
        }
    }
    auto dnnQuery = request.query().get("dnn");
    std::optional<std::string> dnn;
    if(dnnQuery.has_value()){
        std::string valueQuery_instance;
        if(fromStringValue(dnnQuery.value(), valueQuery_instance)){
            dnn = valueQuery_instance;
        }
    }
    auto ueIpv4AddressQuery = request.query().get("ue-ipv4-address");
    std::optional<std::string> ueIpv4Address;
    if(ueIpv4AddressQuery.has_value()){
        std::string valueQuery_instance;
        if(fromStringValue(ueIpv4AddressQuery.value(), valueQuery_instance)){
            ueIpv4Address = valueQuery_instance;
        }
    }
    auto ueIpv6PrefixQuery = request.query().get("ue-ipv6-prefix");
    std::optional<Ipv6Prefix> ueIpv6Prefix;
    if(ueIpv6PrefixQuery.has_value()){
        Ipv6Prefix valueQuery_instance;
        if(fromStringValue(ueIpv6PrefixQuery.value(), valueQuery_instance)){
            ueIpv6Prefix = valueQuery_instance;
        }
    }
    auto portNumberQuery = request.query().get("port-number");
    std::optional<int32_t> portNumber;
    if(portNumberQuery.has_value()){
        int32_t valueQuery_instance;
        if(fromStringValue(portNumberQuery.value(), valueQuery_instance)){
            portNumber = valueQuery_instance;
        }
    }
    
    try {
        this->search_ue_ip_info(snssai, dnn, ueIpv4Address, ueIpv6Prefix, portNumber, response);
    } catch (Pistache::Http::HttpError &e) {
        response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
        return;
    } catch (std::exception &e) {
        const std::pair<Pistache::Http::Code, std::string> errorInfo = this->handleOperationException(e);
        response.send(errorInfo.first, errorInfo.second);
        return;
    }

    } catch (std::exception &e) {
        response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
    }

}

void UEIPInfoGetApi::ueip_info_get_api_default_handler(const Pistache::Rest::Request &, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

} // namespace org::openapitools::server::api

