/**
* UPF GET Private UE IP address Service
* Nupf_GetPrivateUEIPaddr Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.0.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UEIPInfoGetApi.h
 *
 * 
 */

#ifndef UEIPInfoGetApi_H_
#define UEIPInfoGetApi_H_


#include "ApiBase.h"

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include <optional>
#include <utility>

#include "Ipv6Prefix.h"
#include "ProblemDetails.h"
#include "RedirectResponse.h"
#include "Snssai.h"
#include "UeIpInfo.h"
#include <string>

namespace org::openapitools::server::api
{

class  UEIPInfoGetApi : public ApiBase {
public:
    explicit UEIPInfoGetApi(const std::shared_ptr<Pistache::Rest::Router>& rtr);
    virtual ~UEIPInfoGetApi() = default;
    void init();

    static const std::string base;

private:
    void setupRoutes();

    void search_ue_ip_info_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void ueip_info_get_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    /// <summary>
    /// Helper function to handle unexpected Exceptions during Parameter parsing and validation.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(const std::exception& ex) const noexcept;

    /// <summary>
    /// Helper function to handle unexpected Exceptions during processing of the request in handler functions.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(const std::exception& ex) const noexcept;

    /// <summary>
    /// Search UeIpInfo for a PDU session from the UeIpInfo
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="snssai">Slice of the PDU session (optional, default to nullptr)</param>
    /// <param name="dnn">Dnn of the PDU session (optional, default to &quot;&quot;)</param>
    /// <param name="ueIpv4Address">IPv4 address of the UE (optional, default to &quot;&quot;)</param>
    /// <param name="ueIpv6Prefix">IPv6 prefix of the UE (optional, default to &quot;&quot;)</param>
    /// <param name="portNumber">UDP or TCP port associated with the public address (optional, default to 0)</param>
    virtual void search_ue_ip_info(const org::openapitools::server::model::std::optional<Snssai> &snssai, const std::optional<std::string> &dnn, const std::optional<std::string> &ueIpv4Address, const org::openapitools::server::model::std::optional<Ipv6Prefix> &ueIpv6Prefix, const std::optional<int32_t> &portNumber, Pistache::Http::ResponseWriter &response) = 0;

};

} // namespace org::openapitools::server::api

#endif /* UEIPInfoGetApi_H_ */

