/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

#ifndef __PFCP_LIMITS_H__
#define __PFCP_LIMITS_H__

#define PFCP_PREDEFINED_RULES_NAME_MAX_LEN 256
#define PFCP_APPLICATION_ID_MAX_LEN 256
#define PFCP_FRAMED_IPV6_ROUTE_MAX_LEN 256
#define PFCP_FRAMED_ROUTE_MAX_LEN 256
#define PFCP_NETWORK_INSTANCE_MAX_LEN 256
#define PFCP_SDF_FLOW_DESC_MAX_LEN 256
#define PFCP_HEADER_FIELD_NAME_MAX_LEN 256
#define PFCP_HEADER_FIELD_VALUE_MAX_LEN 256
#define PFCP_FORWARDING_POLICY_ID_MAX_LEN 256

#endif  // __PFCP_LIMITS_H__