/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ApplicationRelatedInformation.h
 *
 * Application Related Information
 */

#ifndef ApplicationRelatedInformation_H_
#define ApplicationRelatedInformation_H_


#include <string>
#include "DomainInformation.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Application Related Information
/// </summary>
class  ApplicationRelatedInformation
{
public:
    ApplicationRelatedInformation();
    virtual ~ApplicationRelatedInformation() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const ApplicationRelatedInformation& rhs) const;
    bool operator!=(const ApplicationRelatedInformation& rhs) const;

    /////////////////////////////////////////////
    /// ApplicationRelatedInformation members

    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::std::string> getUrls() const;
    void setUrls(std::vector<org::openapitools::server::model::std::string> const& value);
    bool urlsIsSet() const;
    void unsetUrls();
    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::DomainInformation> getDomainInfoList() const;
    void setDomainInfoList(std::vector<org::openapitools::server::model::DomainInformation> const& value);
    bool domainInfoListIsSet() const;
    void unsetDomainInfoList();

    friend  void to_json(nlohmann::json& j, const ApplicationRelatedInformation& o);
    friend  void from_json(const nlohmann::json& j, ApplicationRelatedInformation& o);
protected:
    std::vector<org::openapitools::server::model::std::string> m_Urls;
    bool m_UrlsIsSet;
    std::vector<org::openapitools::server::model::DomainInformation> m_DomainInfoList;
    bool m_DomainInfoListIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* ApplicationRelatedInformation_H_ */
