/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "ApplicationRelatedInformation.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

ApplicationRelatedInformation::ApplicationRelatedInformation()
{
    m_UrlsIsSet = false;
    m_DomainInfoListIsSet = false;
    
}

void ApplicationRelatedInformation::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool ApplicationRelatedInformation::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool ApplicationRelatedInformation::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "ApplicationRelatedInformation" : pathPrefix;

         
    if (urlsIsSet())
    {
        const std::vector<org::openapitools::server::model::std::string>& value = m_Urls;
        const std::string currentValuePath = _pathPrefix + ".urls";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const std::string& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        
 
                i++;
            }
        }

    }
         
    if (domainInfoListIsSet())
    {
        const std::vector<org::openapitools::server::model::DomainInformation>& value = m_DomainInfoList;
        const std::string currentValuePath = _pathPrefix + ".domainInfoList";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const org::openapitools::server::model::DomainInformation& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".domainInfoList") && success;
 
                i++;
            }
        }

    }
    
    return success;
}

bool ApplicationRelatedInformation::operator==(const ApplicationRelatedInformation& rhs) const
{
    return
    
    
    
    ((!urlsIsSet() && !rhs.urlsIsSet()) || (urlsIsSet() && rhs.urlsIsSet() && getUrls() == rhs.getUrls())) &&
    
    
    ((!domainInfoListIsSet() && !rhs.domainInfoListIsSet()) || (domainInfoListIsSet() && rhs.domainInfoListIsSet() && getDomainInfoList() == rhs.getDomainInfoList()))
    
    ;
}

bool ApplicationRelatedInformation::operator!=(const ApplicationRelatedInformation& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const ApplicationRelatedInformation& o)
{
    j = nlohmann::json();
    if(o.urlsIsSet() || !o.m_Urls.empty())
        j["urls"] = o.m_Urls;
    if(o.domainInfoListIsSet() || !o.m_DomainInfoList.empty())
        j["domainInfoList"] = o.m_DomainInfoList;
    
}

void from_json(const nlohmann::json& j, ApplicationRelatedInformation& o)
{
    if(j.find("urls") != j.end())
    {
        j.at("urls").get_to(o.m_Urls);
        o.m_UrlsIsSet = true;
    } 
    if(j.find("domainInfoList") != j.end())
    {
        j.at("domainInfoList").get_to(o.m_DomainInfoList);
        o.m_DomainInfoListIsSet = true;
    } 
    
}

std::vector<org::openapitools::server::model::std::string> ApplicationRelatedInformation::getUrls() const
{
    return m_Urls;
}
void ApplicationRelatedInformation::setUrls(std::vector<org::openapitools::server::model::std::string> const& value)
{
    m_Urls = value;
    m_UrlsIsSet = true;
}
bool ApplicationRelatedInformation::urlsIsSet() const
{
    return m_UrlsIsSet;
}
void ApplicationRelatedInformation::unsetUrls()
{
    m_UrlsIsSet = false;
}
std::vector<org::openapitools::server::model::DomainInformation> ApplicationRelatedInformation::getDomainInfoList() const
{
    return m_DomainInfoList;
}
void ApplicationRelatedInformation::setDomainInfoList(std::vector<org::openapitools::server::model::DomainInformation> const& value)
{
    m_DomainInfoList = value;
    m_DomainInfoListIsSet = true;
}
bool ApplicationRelatedInformation::domainInfoListIsSet() const
{
    return m_DomainInfoListIsSet;
}
void ApplicationRelatedInformation::unsetDomainInfoList()
{
    m_DomainInfoListIsSet = false;
}


} // namespace org::openapitools::server::model

