/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "CreateEventSubscription.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

CreateEventSubscription::CreateEventSubscription()
{
    m_SupportedFeatures = "";
    m_SupportedFeaturesIsSet = false;
    
}

void CreateEventSubscription::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool CreateEventSubscription::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool CreateEventSubscription::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "CreateEventSubscription" : pathPrefix;

             
    if (supportedFeaturesIsSet())
    {
        const std::string& value = m_SupportedFeatures;
        const std::string currentValuePath = _pathPrefix + ".supportedFeatures";
                
        

    }
    
    return success;
}

bool CreateEventSubscription::operator==(const CreateEventSubscription& rhs) const
{
    return
    
    
    (getSubscription() == rhs.getSubscription())
     &&
    
    
    ((!supportedFeaturesIsSet() && !rhs.supportedFeaturesIsSet()) || (supportedFeaturesIsSet() && rhs.supportedFeaturesIsSet() && getSupportedFeatures() == rhs.getSupportedFeatures()))
    
    ;
}

bool CreateEventSubscription::operator!=(const CreateEventSubscription& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const CreateEventSubscription& o)
{
    j = nlohmann::json();
    j["subscription"] = o.m_Subscription;
    if(o.supportedFeaturesIsSet())
        j["supportedFeatures"] = o.m_SupportedFeatures;
    
}

void from_json(const nlohmann::json& j, CreateEventSubscription& o)
{
    j.at("subscription").get_to(o.m_Subscription);
    if(j.find("supportedFeatures") != j.end())
    {
        j.at("supportedFeatures").get_to(o.m_SupportedFeatures);
        o.m_SupportedFeaturesIsSet = true;
    } 
    
}

org::openapitools::server::model::UpfEventSubscription CreateEventSubscription::getSubscription() const
{
    return m_Subscription;
}
void CreateEventSubscription::setSubscription(org::openapitools::server::model::UpfEventSubscription const& value)
{
    m_Subscription = value;
}
std::string CreateEventSubscription::getSupportedFeatures() const
{
    return m_SupportedFeatures;
}
void CreateEventSubscription::setSupportedFeatures(std::string const& value)
{
    m_SupportedFeatures = value;
    m_SupportedFeaturesIsSet = true;
}
bool CreateEventSubscription::supportedFeaturesIsSet() const
{
    return m_SupportedFeaturesIsSet;
}
void CreateEventSubscription::unsetSupportedFeatures()
{
    m_SupportedFeaturesIsSet = false;
}


} // namespace org::openapitools::server::model

