/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * CreatedEventSubscription.h
 *
 * Data within UPF Create Event Subscription Response
 */

#ifndef CreatedEventSubscription_H_
#define CreatedEventSubscription_H_


#include "UpfEventSubscription.h"
#include <string>
#include "NotificationItem.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Data within UPF Create Event Subscription Response
/// </summary>
class  CreatedEventSubscription
{
public:
    CreatedEventSubscription();
    virtual ~CreatedEventSubscription() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const CreatedEventSubscription& rhs) const;
    bool operator!=(const CreatedEventSubscription& rhs) const;

    /////////////////////////////////////////////
    /// CreatedEventSubscription members

    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::UpfEventSubscription getSubscription() const;
    void setSubscription(org::openapitools::server::model::UpfEventSubscription const& value);
    /// <summary>
    /// String providing an URI formatted according to RFC 3986.
    /// </summary>
    std::string getSubscriptionId() const;
    void setSubscriptionId(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::NotificationItem> getReportList() const;
    void setReportList(std::vector<org::openapitools::server::model::NotificationItem> const& value);
    bool reportListIsSet() const;
    void unsetReportList();
    /// <summary>
    /// A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \&quot;0\&quot; to \&quot;9\&quot;,  \&quot;a\&quot; to \&quot;f\&quot; or \&quot;A\&quot; to \&quot;F\&quot; and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported. 
    /// </summary>
    std::string getSupportedFeatures() const;
    void setSupportedFeatures(std::string const& value);
    bool supportedFeaturesIsSet() const;
    void unsetSupportedFeatures();

    friend  void to_json(nlohmann::json& j, const CreatedEventSubscription& o);
    friend  void from_json(const nlohmann::json& j, CreatedEventSubscription& o);
protected:
    org::openapitools::server::model::UpfEventSubscription m_Subscription;

    std::string m_SubscriptionId;

    std::vector<org::openapitools::server::model::NotificationItem> m_ReportList;
    bool m_ReportListIsSet;
    std::string m_SupportedFeatures;
    bool m_SupportedFeaturesIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* CreatedEventSubscription_H_ */
