/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "DomainInformation.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

DomainInformation::DomainInformation()
{
    m_DomainName = "";
    
}

void DomainInformation::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool DomainInformation::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool DomainInformation::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "DomainInformation" : pathPrefix;

         
    
    /* DomainName */ {
        const std::string& value = m_DomainName;
        const std::string currentValuePath = _pathPrefix + ".domainName";
                
        
        if (value.length() < 4)
        {
            success = false;
            msg << currentValuePath << ": must be at least 4 characters long;";
        }
        if (value.length() > 253)
        {
            success = false;
            msg << currentValuePath << ": must be at most 253 characters long;";
        }

    }
    
    return success;
}

bool DomainInformation::operator==(const DomainInformation& rhs) const
{
    return
    
    
    (getDomainName() == rhs.getDomainName())
    
    
    ;
}

bool DomainInformation::operator!=(const DomainInformation& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const DomainInformation& o)
{
    j = nlohmann::json();
    j["domainName"] = o.m_DomainName;
    
}

void from_json(const nlohmann::json& j, DomainInformation& o)
{
    j.at("domainName").get_to(o.m_DomainName);
    
}

std::string DomainInformation::getDomainName() const
{
    return m_DomainName;
}
void DomainInformation::setDomainName(std::string const& value)
{
    m_DomainName = value;
}


} // namespace org::openapitools::server::model

