/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * DomainInformation.h
 *
 * Domain Information
 */

#ifndef DomainInformation_H_
#define DomainInformation_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Domain Information
/// </summary>
class  DomainInformation
{
public:
    DomainInformation();
    virtual ~DomainInformation() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const DomainInformation& rhs) const;
    bool operator!=(const DomainInformation& rhs) const;

    /////////////////////////////////////////////
    /// DomainInformation members

    /// <summary>
    /// Fully Qualified Domain Name
    /// </summary>
    std::string getDomainName() const;
    void setDomainName(std::string const& value);

    friend  void to_json(nlohmann::json& j, const DomainInformation& o);
    friend  void from_json(const nlohmann::json& j, DomainInformation& o);
protected:
    std::string m_DomainName;

    
};

} // namespace org::openapitools::server::model

#endif /* DomainInformation_H_ */
