/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "MeasurementType.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

MeasurementType::MeasurementType()
{
    
}

void MeasurementType::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool MeasurementType::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool MeasurementType::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "MeasurementType" : pathPrefix;

    
    return success;
}

bool MeasurementType::operator==(const MeasurementType& rhs) const
{
    return
    
    
    ;
}

bool MeasurementType::operator!=(const MeasurementType& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const MeasurementType& o)
{
    j = nlohmann::json();
    
}

void from_json(const nlohmann::json& j, MeasurementType& o)
{
    
}



} // namespace org::openapitools::server::model

