/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * MeasurementType.h
 *
 * Measurement Type
 */

#ifndef MeasurementType_H_
#define MeasurementType_H_


#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Measurement Type
/// </summary>
class  MeasurementType
{
public:
    MeasurementType();
    virtual ~MeasurementType() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const MeasurementType& rhs) const;
    bool operator!=(const MeasurementType& rhs) const;

    /////////////////////////////////////////////
    /// MeasurementType members


    friend  void to_json(nlohmann::json& j, const MeasurementType& o);
    friend  void from_json(const nlohmann::json& j, MeasurementType& o);
protected:
    
};

} // namespace org::openapitools::server::model

#endif /* MeasurementType_H_ */
