/**
* UPF GET Private UE IP address Service
* Nupf_GetPrivateUEIPaddr Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.0.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "NFType.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

NFType::NFType()
{
    
}

void NFType::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool NFType::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool NFType::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "NFType" : pathPrefix;

    
    return success;
}

bool NFType::operator==(const NFType& rhs) const
{
    return
    
    
    ;
}

bool NFType::operator!=(const NFType& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const NFType& o)
{
    j = nlohmann::json();
    
}

void from_json(const nlohmann::json& j, NFType& o)
{
    
}



} // namespace org::openapitools::server::model

