/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * NotificationItem.h
 *
 * represents a report on one subscribed event
 */

#ifndef NotificationItem_H_
#define NotificationItem_H_


#include <string>
#include "Ipv6Prefix.h"
#include "TscManagementInfo.h"
#include "EventType.h"
#include "QosMonitoringMeasurement.h"
#include "Snssai.h"
#include <vector>
#include "UserDataUsageMeasurements.h"
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// represents a report on one subscribed event
/// </summary>
class  NotificationItem
{
public:
    NotificationItem();
    virtual ~NotificationItem() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const NotificationItem& rhs) const;
    bool operator!=(const NotificationItem& rhs) const;

    /////////////////////////////////////////////
    /// NotificationItem members

    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::EventType getEventType() const;
    void setEventType(org::openapitools::server::model::EventType const& value);
    /// <summary>
    /// String identifying a IPv4 address formatted in the &#39;dotted decimal&#39; notation as defined in RFC 1166. 
    /// </summary>
    std::string getUeIpv4Addr() const;
    void setUeIpv4Addr(std::string const& value);
    bool ueIpv4AddrIsSet() const;
    void unsetUeIpv4Addr();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::Ipv6Prefix getUeIpv6Prefix() const;
    void setUeIpv6Prefix(org::openapitools::server::model::Ipv6Prefix const& value);
    bool ueIpv6PrefixIsSet() const;
    void unsetUeIpv6Prefix();
    /// <summary>
    /// String identifying a MAC address formatted in the hexadecimal notation according to clause 1.1 and clause 2.1 of RFC 7042. 
    /// </summary>
    std::string getUeMacAddr() const;
    void setUeMacAddr(std::string const& value);
    bool ueMacAddrIsSet() const;
    void unsetUeMacAddr();
    /// <summary>
    /// String representing a Data Network as defined in clause 9A of 3GPP TS 23.003;  it shall contain either a DNN Network Identifier, or a full DNN with both the Network  Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots  (e.g. \&quot;Label1.Label2.Label3\&quot;). 
    /// </summary>
    std::string getDnn() const;
    void setDnn(std::string const& value);
    bool dnnIsSet() const;
    void unsetDnn();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::Snssai getSnssai() const;
    void setSnssai(org::openapitools::server::model::Snssai const& value);
    bool snssaiIsSet() const;
    void unsetSnssai();
    /// <summary>
    /// String identifying a Gpsi shall contain either an External Id or an MSISDN.  It shall be formatted as follows -External Identifier&#x3D; \&quot;extid-&#39;extid&#39;, where &#39;extid&#39;  shall be formatted according to clause 19.7.2 of 3GPP TS 23.003 that describes an  External Identifier.  
    /// </summary>
    std::string getGpsi() const;
    void setGpsi(std::string const& value);
    bool gpsiIsSet() const;
    void unsetGpsi();
    /// <summary>
    /// String identifying a Supi that shall contain either an IMSI, a network specific identifier, a Global Cable Identifier (GCI) or a Global Line Identifier (GLI) as specified in clause  2.2A of 3GPP TS 23.003. It shall be formatted as follows  - for an IMSI \&quot;imsi-&lt;imsi&gt;\&quot;, where &lt;imsi&gt; shall be formatted according to clause 2.2    of 3GPP TS 23.003 that describes an IMSI.  - for a network specific identifier \&quot;nai-&lt;nai&gt;, where &lt;nai&gt; shall be formatted    according to clause 28.7.2 of 3GPP TS 23.003 that describes an NAI.  - for a GCI \&quot;gci-&lt;gci&gt;\&quot;, where &lt;gci&gt; shall be formatted according to clause 28.15.2    of 3GPP TS 23.003.  - for a GLI \&quot;gli-&lt;gli&gt;\&quot;, where &lt;gli&gt; shall be formatted according to clause 28.16.2 of    3GPP TS 23.003.To enable that the value is used as part of an URI, the string shall    only contain characters allowed according to the \&quot;lower-with-hyphen\&quot; naming convention    defined in 3GPP TS 29.501. 
    /// </summary>
    std::string getSupi() const;
    void setSupi(std::string const& value);
    bool supiIsSet() const;
    void unsetSupi();
    /// <summary>
    /// string with format &#39;date-time&#39; as defined in OpenAPI.
    /// </summary>
    std::string getTimeStamp() const;
    void setTimeStamp(std::string const& value);
    /// <summary>
    /// string with format &#39;date-time&#39; as defined in OpenAPI.
    /// </summary>
    std::string getStartTime() const;
    void setStartTime(std::string const& value);
    bool startTimeIsSet() const;
    void unsetStartTime();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::QosMonitoringMeasurement getQosMonitoringMeasurement() const;
    void setQosMonitoringMeasurement(org::openapitools::server::model::QosMonitoringMeasurement const& value);
    bool qosMonitoringMeasurementIsSet() const;
    void unsetQosMonitoringMeasurement();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::TscManagementInfo getTscMngtInfo() const;
    void setTscMngtInfo(org::openapitools::server::model::TscManagementInfo const& value);
    bool tscMngtInfoIsSet() const;
    void unsetTscMngtInfo();
    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::UserDataUsageMeasurements> getUserDataUsageMeasurements() const;
    void setUserDataUsageMeasurements(std::vector<org::openapitools::server::model::UserDataUsageMeasurements> const& value);
    bool userDataUsageMeasurementsIsSet() const;
    void unsetUserDataUsageMeasurements();

    friend  void to_json(nlohmann::json& j, const NotificationItem& o);
    friend  void from_json(const nlohmann::json& j, NotificationItem& o);
protected:
    org::openapitools::server::model::EventType m_EventType;

    std::string m_UeIpv4Addr;
    bool m_UeIpv4AddrIsSet;
    org::openapitools::server::model::Ipv6Prefix m_UeIpv6Prefix;
    bool m_UeIpv6PrefixIsSet;
    std::string m_UeMacAddr;
    bool m_UeMacAddrIsSet;
    std::string m_Dnn;
    bool m_DnnIsSet;
    org::openapitools::server::model::Snssai m_Snssai;
    bool m_SnssaiIsSet;
    std::string m_Gpsi;
    bool m_GpsiIsSet;
    std::string m_Supi;
    bool m_SupiIsSet;
    std::string m_TimeStamp;

    std::string m_StartTime;
    bool m_StartTimeIsSet;
    org::openapitools::server::model::QosMonitoringMeasurement m_QosMonitoringMeasurement;
    bool m_QosMonitoringMeasurementIsSet;
    org::openapitools::server::model::TscManagementInfo m_TscMngtInfo;
    bool m_TscMngtInfoIsSet;
    std::vector<org::openapitools::server::model::UserDataUsageMeasurements> m_UserDataUsageMeasurements;
    bool m_UserDataUsageMeasurementsIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* NotificationItem_H_ */
