/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "NotificationData.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

NotificationData::NotificationData()
{
    m_CorrelationId = "";
    m_CorrelationIdIsSet = false;
    
}

void NotificationData::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool NotificationData::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool NotificationData::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "NotificationData" : pathPrefix;

         
    
    /* NotificationItems */ {
        const std::vector<org::openapitools::server::model::NotificationItem>& value = m_NotificationItems;
        const std::string currentValuePath = _pathPrefix + ".notificationItems";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const org::openapitools::server::model::NotificationItem& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".notificationItems") && success;
 
                i++;
            }
        }

    }
        
    return success;
}

bool NotificationData::operator==(const NotificationData& rhs) const
{
    return
    
    
    (getNotificationItems() == rhs.getNotificationItems())
     &&
    
    
    ((!correlationIdIsSet() && !rhs.correlationIdIsSet()) || (correlationIdIsSet() && rhs.correlationIdIsSet() && getCorrelationId() == rhs.getCorrelationId()))
    
    ;
}

bool NotificationData::operator!=(const NotificationData& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const NotificationData& o)
{
    j = nlohmann::json();
    j["notificationItems"] = o.m_NotificationItems;
    if(o.correlationIdIsSet())
        j["correlationId"] = o.m_CorrelationId;
    
}

void from_json(const nlohmann::json& j, NotificationData& o)
{
    j.at("notificationItems").get_to(o.m_NotificationItems);
    if(j.find("correlationId") != j.end())
    {
        j.at("correlationId").get_to(o.m_CorrelationId);
        o.m_CorrelationIdIsSet = true;
    } 
    
}

std::vector<org::openapitools::server::model::NotificationItem> NotificationData::getNotificationItems() const
{
    return m_NotificationItems;
}
void NotificationData::setNotificationItems(std::vector<org::openapitools::server::model::NotificationItem> const& value)
{
    m_NotificationItems = value;
}
std::string NotificationData::getCorrelationId() const
{
    return m_CorrelationId;
}
void NotificationData::setCorrelationId(std::string const& value)
{
    m_CorrelationId = value;
    m_CorrelationIdIsSet = true;
}
bool NotificationData::correlationIdIsSet() const
{
    return m_CorrelationIdIsSet;
}
void NotificationData::unsetCorrelationId()
{
    m_CorrelationIdIsSet = false;
}


} // namespace org::openapitools::server::model

