/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * NotificationData.h
 *
 * the list of NotificationItems
 */

#ifndef NotificationData_H_
#define NotificationData_H_


#include <string>
#include "NotificationItem.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// the list of NotificationItems
/// </summary>
class  NotificationData
{
public:
    NotificationData();
    virtual ~NotificationData() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const NotificationData& rhs) const;
    bool operator!=(const NotificationData& rhs) const;

    /////////////////////////////////////////////
    /// NotificationData members

    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::NotificationItem> getNotificationItems() const;
    void setNotificationItems(std::vector<org::openapitools::server::model::NotificationItem> const& value);
    /// <summary>
    /// 
    /// </summary>
    std::string getCorrelationId() const;
    void setCorrelationId(std::string const& value);
    bool correlationIdIsSet() const;
    void unsetCorrelationId();

    friend  void to_json(nlohmann::json& j, const NotificationData& o);
    friend  void from_json(const nlohmann::json& j, NotificationData& o);
protected:
    std::vector<org::openapitools::server::model::NotificationItem> m_NotificationItems;

    std::string m_CorrelationId;
    bool m_CorrelationIdIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* NotificationData_H_ */
