/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "NotificationItem.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

NotificationItem::NotificationItem()
{
    m_UeIpv4Addr = "";
    m_UeIpv4AddrIsSet = false;
    m_UeIpv6PrefixIsSet = false;
    m_UeMacAddr = "";
    m_UeMacAddrIsSet = false;
    m_Dnn = "";
    m_DnnIsSet = false;
    m_SnssaiIsSet = false;
    m_Gpsi = "";
    m_GpsiIsSet = false;
    m_Supi = "";
    m_SupiIsSet = false;
    m_TimeStamp = "";
    m_StartTime = "";
    m_StartTimeIsSet = false;
    m_QosMonitoringMeasurementIsSet = false;
    m_TscMngtInfoIsSet = false;
    m_UserDataUsageMeasurementsIsSet = false;
    
}

void NotificationItem::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool NotificationItem::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool NotificationItem::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "NotificationItem" : pathPrefix;

             
    if (ueIpv4AddrIsSet())
    {
        const std::string& value = m_UeIpv4Addr;
        const std::string currentValuePath = _pathPrefix + ".ueIpv4Addr";
                
        

    }
             
    if (ueMacAddrIsSet())
    {
        const std::string& value = m_UeMacAddr;
        const std::string currentValuePath = _pathPrefix + ".ueMacAddr";
                
        

    }
                 
    if (gpsiIsSet())
    {
        const std::string& value = m_Gpsi;
        const std::string currentValuePath = _pathPrefix + ".gpsi";
                
        

    }
         
    if (supiIsSet())
    {
        const std::string& value = m_Supi;
        const std::string currentValuePath = _pathPrefix + ".supi";
                
        

    }
                         
    if (userDataUsageMeasurementsIsSet())
    {
        const std::vector<org::openapitools::server::model::UserDataUsageMeasurements>& value = m_UserDataUsageMeasurements;
        const std::string currentValuePath = _pathPrefix + ".userDataUsageMeasurements";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const org::openapitools::server::model::UserDataUsageMeasurements& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".userDataUsageMeasurements") && success;
 
                i++;
            }
        }

    }
    
    return success;
}

bool NotificationItem::operator==(const NotificationItem& rhs) const
{
    return
    
    
    (getEventType() == rhs.getEventType())
     &&
    
    
    ((!ueIpv4AddrIsSet() && !rhs.ueIpv4AddrIsSet()) || (ueIpv4AddrIsSet() && rhs.ueIpv4AddrIsSet() && getUeIpv4Addr() == rhs.getUeIpv4Addr())) &&
    
    
    ((!ueIpv6PrefixIsSet() && !rhs.ueIpv6PrefixIsSet()) || (ueIpv6PrefixIsSet() && rhs.ueIpv6PrefixIsSet() && getUeIpv6Prefix() == rhs.getUeIpv6Prefix())) &&
    
    
    ((!ueMacAddrIsSet() && !rhs.ueMacAddrIsSet()) || (ueMacAddrIsSet() && rhs.ueMacAddrIsSet() && getUeMacAddr() == rhs.getUeMacAddr())) &&
    
    
    ((!dnnIsSet() && !rhs.dnnIsSet()) || (dnnIsSet() && rhs.dnnIsSet() && getDnn() == rhs.getDnn())) &&
    
    
    ((!snssaiIsSet() && !rhs.snssaiIsSet()) || (snssaiIsSet() && rhs.snssaiIsSet() && getSnssai() == rhs.getSnssai())) &&
    
    
    ((!gpsiIsSet() && !rhs.gpsiIsSet()) || (gpsiIsSet() && rhs.gpsiIsSet() && getGpsi() == rhs.getGpsi())) &&
    
    
    ((!supiIsSet() && !rhs.supiIsSet()) || (supiIsSet() && rhs.supiIsSet() && getSupi() == rhs.getSupi())) &&
    
    (getTimeStamp() == rhs.getTimeStamp())
     &&
    
    
    ((!startTimeIsSet() && !rhs.startTimeIsSet()) || (startTimeIsSet() && rhs.startTimeIsSet() && getStartTime() == rhs.getStartTime())) &&
    
    
    ((!qosMonitoringMeasurementIsSet() && !rhs.qosMonitoringMeasurementIsSet()) || (qosMonitoringMeasurementIsSet() && rhs.qosMonitoringMeasurementIsSet() && getQosMonitoringMeasurement() == rhs.getQosMonitoringMeasurement())) &&
    
    
    ((!tscMngtInfoIsSet() && !rhs.tscMngtInfoIsSet()) || (tscMngtInfoIsSet() && rhs.tscMngtInfoIsSet() && getTscMngtInfo() == rhs.getTscMngtInfo())) &&
    
    
    ((!userDataUsageMeasurementsIsSet() && !rhs.userDataUsageMeasurementsIsSet()) || (userDataUsageMeasurementsIsSet() && rhs.userDataUsageMeasurementsIsSet() && getUserDataUsageMeasurements() == rhs.getUserDataUsageMeasurements()))
    
    ;
}

bool NotificationItem::operator!=(const NotificationItem& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const NotificationItem& o)
{
    j = nlohmann::json();
    j["eventType"] = o.m_EventType;
    if(o.ueIpv4AddrIsSet())
        j["ueIpv4Addr"] = o.m_UeIpv4Addr;
    if(o.ueIpv6PrefixIsSet())
        j["ueIpv6Prefix"] = o.m_UeIpv6Prefix;
    if(o.ueMacAddrIsSet())
        j["ueMacAddr"] = o.m_UeMacAddr;
    if(o.dnnIsSet())
        j["dnn"] = o.m_Dnn;
    if(o.snssaiIsSet())
        j["snssai"] = o.m_Snssai;
    if(o.gpsiIsSet())
        j["gpsi"] = o.m_Gpsi;
    if(o.supiIsSet())
        j["supi"] = o.m_Supi;
    j["timeStamp"] = o.m_TimeStamp;
    if(o.startTimeIsSet())
        j["startTime"] = o.m_StartTime;
    if(o.qosMonitoringMeasurementIsSet())
        j["qosMonitoringMeasurement"] = o.m_QosMonitoringMeasurement;
    if(o.tscMngtInfoIsSet())
        j["tscMngtInfo"] = o.m_TscMngtInfo;
    if(o.userDataUsageMeasurementsIsSet() || !o.m_UserDataUsageMeasurements.empty())
        j["userDataUsageMeasurements"] = o.m_UserDataUsageMeasurements;
    
}

void from_json(const nlohmann::json& j, NotificationItem& o)
{
    j.at("eventType").get_to(o.m_EventType);
    if(j.find("ueIpv4Addr") != j.end())
    {
        j.at("ueIpv4Addr").get_to(o.m_UeIpv4Addr);
        o.m_UeIpv4AddrIsSet = true;
    } 
    if(j.find("ueIpv6Prefix") != j.end())
    {
        j.at("ueIpv6Prefix").get_to(o.m_UeIpv6Prefix);
        o.m_UeIpv6PrefixIsSet = true;
    } 
    if(j.find("ueMacAddr") != j.end())
    {
        j.at("ueMacAddr").get_to(o.m_UeMacAddr);
        o.m_UeMacAddrIsSet = true;
    } 
    if(j.find("dnn") != j.end())
    {
        j.at("dnn").get_to(o.m_Dnn);
        o.m_DnnIsSet = true;
    } 
    if(j.find("snssai") != j.end())
    {
        j.at("snssai").get_to(o.m_Snssai);
        o.m_SnssaiIsSet = true;
    } 
    if(j.find("gpsi") != j.end())
    {
        j.at("gpsi").get_to(o.m_Gpsi);
        o.m_GpsiIsSet = true;
    } 
    if(j.find("supi") != j.end())
    {
        j.at("supi").get_to(o.m_Supi);
        o.m_SupiIsSet = true;
    } 
    j.at("timeStamp").get_to(o.m_TimeStamp);
    if(j.find("startTime") != j.end())
    {
        j.at("startTime").get_to(o.m_StartTime);
        o.m_StartTimeIsSet = true;
    } 
    if(j.find("qosMonitoringMeasurement") != j.end())
    {
        j.at("qosMonitoringMeasurement").get_to(o.m_QosMonitoringMeasurement);
        o.m_QosMonitoringMeasurementIsSet = true;
    } 
    if(j.find("tscMngtInfo") != j.end())
    {
        j.at("tscMngtInfo").get_to(o.m_TscMngtInfo);
        o.m_TscMngtInfoIsSet = true;
    } 
    if(j.find("userDataUsageMeasurements") != j.end())
    {
        j.at("userDataUsageMeasurements").get_to(o.m_UserDataUsageMeasurements);
        o.m_UserDataUsageMeasurementsIsSet = true;
    } 
    
}

org::openapitools::server::model::EventType NotificationItem::getEventType() const
{
    return m_EventType;
}
void NotificationItem::setEventType(org::openapitools::server::model::EventType const& value)
{
    m_EventType = value;
}
std::string NotificationItem::getUeIpv4Addr() const
{
    return m_UeIpv4Addr;
}
void NotificationItem::setUeIpv4Addr(std::string const& value)
{
    m_UeIpv4Addr = value;
    m_UeIpv4AddrIsSet = true;
}
bool NotificationItem::ueIpv4AddrIsSet() const
{
    return m_UeIpv4AddrIsSet;
}
void NotificationItem::unsetUeIpv4Addr()
{
    m_UeIpv4AddrIsSet = false;
}
org::openapitools::server::model::Ipv6Prefix NotificationItem::getUeIpv6Prefix() const
{
    return m_UeIpv6Prefix;
}
void NotificationItem::setUeIpv6Prefix(org::openapitools::server::model::Ipv6Prefix const& value)
{
    m_UeIpv6Prefix = value;
    m_UeIpv6PrefixIsSet = true;
}
bool NotificationItem::ueIpv6PrefixIsSet() const
{
    return m_UeIpv6PrefixIsSet;
}
void NotificationItem::unsetUeIpv6Prefix()
{
    m_UeIpv6PrefixIsSet = false;
}
std::string NotificationItem::getUeMacAddr() const
{
    return m_UeMacAddr;
}
void NotificationItem::setUeMacAddr(std::string const& value)
{
    m_UeMacAddr = value;
    m_UeMacAddrIsSet = true;
}
bool NotificationItem::ueMacAddrIsSet() const
{
    return m_UeMacAddrIsSet;
}
void NotificationItem::unsetUeMacAddr()
{
    m_UeMacAddrIsSet = false;
}
std::string NotificationItem::getDnn() const
{
    return m_Dnn;
}
void NotificationItem::setDnn(std::string const& value)
{
    m_Dnn = value;
    m_DnnIsSet = true;
}
bool NotificationItem::dnnIsSet() const
{
    return m_DnnIsSet;
}
void NotificationItem::unsetDnn()
{
    m_DnnIsSet = false;
}
org::openapitools::server::model::Snssai NotificationItem::getSnssai() const
{
    return m_Snssai;
}
void NotificationItem::setSnssai(org::openapitools::server::model::Snssai const& value)
{
    m_Snssai = value;
    m_SnssaiIsSet = true;
}
bool NotificationItem::snssaiIsSet() const
{
    return m_SnssaiIsSet;
}
void NotificationItem::unsetSnssai()
{
    m_SnssaiIsSet = false;
}
std::string NotificationItem::getGpsi() const
{
    return m_Gpsi;
}
void NotificationItem::setGpsi(std::string const& value)
{
    m_Gpsi = value;
    m_GpsiIsSet = true;
}
bool NotificationItem::gpsiIsSet() const
{
    return m_GpsiIsSet;
}
void NotificationItem::unsetGpsi()
{
    m_GpsiIsSet = false;
}
std::string NotificationItem::getSupi() const
{
    return m_Supi;
}
void NotificationItem::setSupi(std::string const& value)
{
    m_Supi = value;
    m_SupiIsSet = true;
}
bool NotificationItem::supiIsSet() const
{
    return m_SupiIsSet;
}
void NotificationItem::unsetSupi()
{
    m_SupiIsSet = false;
}
std::string NotificationItem::getTimeStamp() const
{
    return m_TimeStamp;
}
void NotificationItem::setTimeStamp(std::string const& value)
{
    m_TimeStamp = value;
}
std::string NotificationItem::getStartTime() const
{
    return m_StartTime;
}
void NotificationItem::setStartTime(std::string const& value)
{
    m_StartTime = value;
    m_StartTimeIsSet = true;
}
bool NotificationItem::startTimeIsSet() const
{
    return m_StartTimeIsSet;
}
void NotificationItem::unsetStartTime()
{
    m_StartTimeIsSet = false;
}
org::openapitools::server::model::QosMonitoringMeasurement NotificationItem::getQosMonitoringMeasurement() const
{
    return m_QosMonitoringMeasurement;
}
void NotificationItem::setQosMonitoringMeasurement(org::openapitools::server::model::QosMonitoringMeasurement const& value)
{
    m_QosMonitoringMeasurement = value;
    m_QosMonitoringMeasurementIsSet = true;
}
bool NotificationItem::qosMonitoringMeasurementIsSet() const
{
    return m_QosMonitoringMeasurementIsSet;
}
void NotificationItem::unsetQosMonitoringMeasurement()
{
    m_QosMonitoringMeasurementIsSet = false;
}
org::openapitools::server::model::TscManagementInfo NotificationItem::getTscMngtInfo() const
{
    return m_TscMngtInfo;
}
void NotificationItem::setTscMngtInfo(org::openapitools::server::model::TscManagementInfo const& value)
{
    m_TscMngtInfo = value;
    m_TscMngtInfoIsSet = true;
}
bool NotificationItem::tscMngtInfoIsSet() const
{
    return m_TscMngtInfoIsSet;
}
void NotificationItem::unsetTscMngtInfo()
{
    m_TscMngtInfoIsSet = false;
}
std::vector<org::openapitools::server::model::UserDataUsageMeasurements> NotificationItem::getUserDataUsageMeasurements() const
{
    return m_UserDataUsageMeasurements;
}
void NotificationItem::setUserDataUsageMeasurements(std::vector<org::openapitools::server::model::UserDataUsageMeasurements> const& value)
{
    m_UserDataUsageMeasurements = value;
    m_UserDataUsageMeasurementsIsSet = true;
}
bool NotificationItem::userDataUsageMeasurementsIsSet() const
{
    return m_UserDataUsageMeasurementsIsSet;
}
void NotificationItem::unsetUserDataUsageMeasurements()
{
    m_UserDataUsageMeasurementsIsSet = false;
}


} // namespace org::openapitools::server::model

