/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * PatchOperation.h
 *
 * Operations as defined in IETF RFC 6902.
 */

#ifndef PatchOperation_H_
#define PatchOperation_H_


#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Operations as defined in IETF RFC 6902.
/// </summary>
class  PatchOperation
{
public:
    PatchOperation();
    virtual ~PatchOperation() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const PatchOperation& rhs) const;
    bool operator!=(const PatchOperation& rhs) const;

    /////////////////////////////////////////////
    /// PatchOperation members


    friend  void to_json(nlohmann::json& j, const PatchOperation& o);
    friend  void from_json(const nlohmann::json& j, PatchOperation& o);
protected:
    
};

} // namespace org::openapitools::server::model

#endif /* PatchOperation_H_ */
