/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * QosMonitoringMeasurement.h
 *
 * QoS Monitoring Measurement information
 */

#ifndef QosMonitoringMeasurement_H_
#define QosMonitoringMeasurement_H_


#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// QoS Monitoring Measurement information
/// </summary>
class  QosMonitoringMeasurement
{
public:
    QosMonitoringMeasurement();
    virtual ~QosMonitoringMeasurement() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const QosMonitoringMeasurement& rhs) const;
    bool operator!=(const QosMonitoringMeasurement& rhs) const;

    /////////////////////////////////////////////
    /// QosMonitoringMeasurement members

    /// <summary>
    /// Integer where the allowed values correspond to the value range of an unsigned 32-bit integer. 
    /// </summary>
    int32_t getDlPacketDelay() const;
    void setDlPacketDelay(int32_t const value);
    bool dlPacketDelayIsSet() const;
    void unsetDlPacketDelay();
    /// <summary>
    /// Integer where the allowed values correspond to the value range of an unsigned 32-bit integer. 
    /// </summary>
    int32_t getUlPacketDelay() const;
    void setUlPacketDelay(int32_t const value);
    bool ulPacketDelayIsSet() const;
    void unsetUlPacketDelay();
    /// <summary>
    /// Integer where the allowed values correspond to the value range of an unsigned 32-bit integer. 
    /// </summary>
    int32_t getRtrPacketDelay() const;
    void setRtrPacketDelay(int32_t const value);
    bool rtrPacketDelayIsSet() const;
    void unsetRtrPacketDelay();
    /// <summary>
    /// 
    /// </summary>
    bool isMeasureFailure() const;
    void setMeasureFailure(bool const value);
    bool measureFailureIsSet() const;
    void unsetMeasureFailure();

    friend  void to_json(nlohmann::json& j, const QosMonitoringMeasurement& o);
    friend  void from_json(const nlohmann::json& j, QosMonitoringMeasurement& o);
protected:
    int32_t m_DlPacketDelay;
    bool m_DlPacketDelayIsSet;
    int32_t m_UlPacketDelay;
    bool m_UlPacketDelayIsSet;
    int32_t m_RtrPacketDelay;
    bool m_RtrPacketDelayIsSet;
    bool m_MeasureFailure;
    bool m_MeasureFailureIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* QosMonitoringMeasurement_H_ */
