/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "QosMonitoringMeasurement.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

QosMonitoringMeasurement::QosMonitoringMeasurement()
{
    m_DlPacketDelay = 0;
    m_DlPacketDelayIsSet = false;
    m_UlPacketDelay = 0;
    m_UlPacketDelayIsSet = false;
    m_RtrPacketDelay = 0;
    m_RtrPacketDelayIsSet = false;
    m_MeasureFailure = false;
    m_MeasureFailureIsSet = false;
    
}

void QosMonitoringMeasurement::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool QosMonitoringMeasurement::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool QosMonitoringMeasurement::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "QosMonitoringMeasurement" : pathPrefix;

         
    if (dlPacketDelayIsSet())
    {
        const int32_t& value = m_DlPacketDelay;
        const std::string currentValuePath = _pathPrefix + ".dlPacketDelay";
                
        
        if (value < 0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0;";
        }
        if (value > 4294967295)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 4294967295;";
        }

    }
         
    if (ulPacketDelayIsSet())
    {
        const int32_t& value = m_UlPacketDelay;
        const std::string currentValuePath = _pathPrefix + ".ulPacketDelay";
                
        
        if (value < 0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0;";
        }
        if (value > 4294967295)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 4294967295;";
        }

    }
         
    if (rtrPacketDelayIsSet())
    {
        const int32_t& value = m_RtrPacketDelay;
        const std::string currentValuePath = _pathPrefix + ".rtrPacketDelay";
                
        
        if (value < 0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0;";
        }
        if (value > 4294967295)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 4294967295;";
        }

    }
        
    return success;
}

bool QosMonitoringMeasurement::operator==(const QosMonitoringMeasurement& rhs) const
{
    return
    
    
    
    ((!dlPacketDelayIsSet() && !rhs.dlPacketDelayIsSet()) || (dlPacketDelayIsSet() && rhs.dlPacketDelayIsSet() && getDlPacketDelay() == rhs.getDlPacketDelay())) &&
    
    
    ((!ulPacketDelayIsSet() && !rhs.ulPacketDelayIsSet()) || (ulPacketDelayIsSet() && rhs.ulPacketDelayIsSet() && getUlPacketDelay() == rhs.getUlPacketDelay())) &&
    
    
    ((!rtrPacketDelayIsSet() && !rhs.rtrPacketDelayIsSet()) || (rtrPacketDelayIsSet() && rhs.rtrPacketDelayIsSet() && getRtrPacketDelay() == rhs.getRtrPacketDelay())) &&
    
    
    ((!measureFailureIsSet() && !rhs.measureFailureIsSet()) || (measureFailureIsSet() && rhs.measureFailureIsSet() && isMeasureFailure() == rhs.isMeasureFailure()))
    
    ;
}

bool QosMonitoringMeasurement::operator!=(const QosMonitoringMeasurement& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const QosMonitoringMeasurement& o)
{
    j = nlohmann::json();
    if(o.dlPacketDelayIsSet())
        j["dlPacketDelay"] = o.m_DlPacketDelay;
    if(o.ulPacketDelayIsSet())
        j["ulPacketDelay"] = o.m_UlPacketDelay;
    if(o.rtrPacketDelayIsSet())
        j["rtrPacketDelay"] = o.m_RtrPacketDelay;
    if(o.measureFailureIsSet())
        j["measureFailure"] = o.m_MeasureFailure;
    
}

void from_json(const nlohmann::json& j, QosMonitoringMeasurement& o)
{
    if(j.find("dlPacketDelay") != j.end())
    {
        j.at("dlPacketDelay").get_to(o.m_DlPacketDelay);
        o.m_DlPacketDelayIsSet = true;
    } 
    if(j.find("ulPacketDelay") != j.end())
    {
        j.at("ulPacketDelay").get_to(o.m_UlPacketDelay);
        o.m_UlPacketDelayIsSet = true;
    } 
    if(j.find("rtrPacketDelay") != j.end())
    {
        j.at("rtrPacketDelay").get_to(o.m_RtrPacketDelay);
        o.m_RtrPacketDelayIsSet = true;
    } 
    if(j.find("measureFailure") != j.end())
    {
        j.at("measureFailure").get_to(o.m_MeasureFailure);
        o.m_MeasureFailureIsSet = true;
    } 
    
}

int32_t QosMonitoringMeasurement::getDlPacketDelay() const
{
    return m_DlPacketDelay;
}
void QosMonitoringMeasurement::setDlPacketDelay(int32_t const value)
{
    m_DlPacketDelay = value;
    m_DlPacketDelayIsSet = true;
}
bool QosMonitoringMeasurement::dlPacketDelayIsSet() const
{
    return m_DlPacketDelayIsSet;
}
void QosMonitoringMeasurement::unsetDlPacketDelay()
{
    m_DlPacketDelayIsSet = false;
}
int32_t QosMonitoringMeasurement::getUlPacketDelay() const
{
    return m_UlPacketDelay;
}
void QosMonitoringMeasurement::setUlPacketDelay(int32_t const value)
{
    m_UlPacketDelay = value;
    m_UlPacketDelayIsSet = true;
}
bool QosMonitoringMeasurement::ulPacketDelayIsSet() const
{
    return m_UlPacketDelayIsSet;
}
void QosMonitoringMeasurement::unsetUlPacketDelay()
{
    m_UlPacketDelayIsSet = false;
}
int32_t QosMonitoringMeasurement::getRtrPacketDelay() const
{
    return m_RtrPacketDelay;
}
void QosMonitoringMeasurement::setRtrPacketDelay(int32_t const value)
{
    m_RtrPacketDelay = value;
    m_RtrPacketDelayIsSet = true;
}
bool QosMonitoringMeasurement::rtrPacketDelayIsSet() const
{
    return m_RtrPacketDelayIsSet;
}
void QosMonitoringMeasurement::unsetRtrPacketDelay()
{
    m_RtrPacketDelayIsSet = false;
}
bool QosMonitoringMeasurement::isMeasureFailure() const
{
    return m_MeasureFailure;
}
void QosMonitoringMeasurement::setMeasureFailure(bool const value)
{
    m_MeasureFailure = value;
    m_MeasureFailureIsSet = true;
}
bool QosMonitoringMeasurement::measureFailureIsSet() const
{
    return m_MeasureFailureIsSet;
}
void QosMonitoringMeasurement::unsetMeasureFailure()
{
    m_MeasureFailureIsSet = false;
}


} // namespace org::openapitools::server::model

