/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ReportingSuggestionInformation.h
 *
 * Reporting Suggestion Information
 */

#ifndef ReportingSuggestionInformation_H_
#define ReportingSuggestionInformation_H_


#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Reporting Suggestion Information
/// </summary>
class  ReportingSuggestionInformation
{
public:
    ReportingSuggestionInformation();
    virtual ~ReportingSuggestionInformation() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const ReportingSuggestionInformation& rhs) const;
    bool operator!=(const ReportingSuggestionInformation& rhs) const;

    /////////////////////////////////////////////
    /// ReportingSuggestionInformation members

    /// <summary>
    /// 
    /// </summary>
    bool isReportingUrgency() const;
    void setReportingUrgency(bool const value);
    /// <summary>
    /// indicating a time in seconds.
    /// </summary>
    int32_t getReportingTimeInfo() const;
    void setReportingTimeInfo(int32_t const value);
    bool reportingTimeInfoIsSet() const;
    void unsetReportingTimeInfo();

    friend  void to_json(nlohmann::json& j, const ReportingSuggestionInformation& o);
    friend  void from_json(const nlohmann::json& j, ReportingSuggestionInformation& o);
protected:
    bool m_ReportingUrgency;

    int32_t m_ReportingTimeInfo;
    bool m_ReportingTimeInfoIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* ReportingSuggestionInformation_H_ */
