/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "ReportingSuggestionInformation.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

ReportingSuggestionInformation::ReportingSuggestionInformation()
{
    m_ReportingUrgency = false;
    m_ReportingTimeInfo = 0;
    m_ReportingTimeInfoIsSet = false;
    
}

void ReportingSuggestionInformation::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool ReportingSuggestionInformation::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool ReportingSuggestionInformation::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "ReportingSuggestionInformation" : pathPrefix;

            
    return success;
}

bool ReportingSuggestionInformation::operator==(const ReportingSuggestionInformation& rhs) const
{
    return
    
    
    (isReportingUrgency() == rhs.isReportingUrgency())
     &&
    
    
    ((!reportingTimeInfoIsSet() && !rhs.reportingTimeInfoIsSet()) || (reportingTimeInfoIsSet() && rhs.reportingTimeInfoIsSet() && getReportingTimeInfo() == rhs.getReportingTimeInfo()))
    
    ;
}

bool ReportingSuggestionInformation::operator!=(const ReportingSuggestionInformation& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const ReportingSuggestionInformation& o)
{
    j = nlohmann::json();
    j["reportingUrgency"] = o.m_ReportingUrgency;
    if(o.reportingTimeInfoIsSet())
        j["reportingTimeInfo"] = o.m_ReportingTimeInfo;
    
}

void from_json(const nlohmann::json& j, ReportingSuggestionInformation& o)
{
    j.at("reportingUrgency").get_to(o.m_ReportingUrgency);
    if(j.find("reportingTimeInfo") != j.end())
    {
        j.at("reportingTimeInfo").get_to(o.m_ReportingTimeInfo);
        o.m_ReportingTimeInfoIsSet = true;
    } 
    
}

bool ReportingSuggestionInformation::isReportingUrgency() const
{
    return m_ReportingUrgency;
}
void ReportingSuggestionInformation::setReportingUrgency(bool const value)
{
    m_ReportingUrgency = value;
}
int32_t ReportingSuggestionInformation::getReportingTimeInfo() const
{
    return m_ReportingTimeInfo;
}
void ReportingSuggestionInformation::setReportingTimeInfo(int32_t const value)
{
    m_ReportingTimeInfo = value;
    m_ReportingTimeInfoIsSet = true;
}
bool ReportingSuggestionInformation::reportingTimeInfoIsSet() const
{
    return m_ReportingTimeInfoIsSet;
}
void ReportingSuggestionInformation::unsetReportingTimeInfo()
{
    m_ReportingTimeInfoIsSet = false;
}


} // namespace org::openapitools::server::model

