/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "ThroughputStatisticsMeasurement.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

ThroughputStatisticsMeasurement::ThroughputStatisticsMeasurement()
{
    m_UlAverageThroughput = "";
    m_UlAverageThroughputIsSet = false;
    m_DlAverageThroughput = "";
    m_DlAverageThroughputIsSet = false;
    m_UlPeakThroughput = "";
    m_UlPeakThroughputIsSet = false;
    m_DlPeakThroughPut = "";
    m_DlPeakThroughPutIsSet = false;
    m_UlAveragePacketThroughput = "";
    m_UlAveragePacketThroughputIsSet = false;
    m_DlAveragePacketThroughput = "";
    m_DlAveragePacketThroughputIsSet = false;
    m_UlPeakPacketThroughput = "";
    m_UlPeakPacketThroughputIsSet = false;
    m_DlPeakPacketThroughput = "";
    m_DlPeakPacketThroughputIsSet = false;
    
}

void ThroughputStatisticsMeasurement::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool ThroughputStatisticsMeasurement::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool ThroughputStatisticsMeasurement::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "ThroughputStatisticsMeasurement" : pathPrefix;

         
    if (ulAverageThroughputIsSet())
    {
        const std::string& value = m_UlAverageThroughput;
        const std::string currentValuePath = _pathPrefix + ".ulAverageThroughput";
                
        

    }
         
    if (dlAverageThroughputIsSet())
    {
        const std::string& value = m_DlAverageThroughput;
        const std::string currentValuePath = _pathPrefix + ".dlAverageThroughput";
                
        

    }
         
    if (ulPeakThroughputIsSet())
    {
        const std::string& value = m_UlPeakThroughput;
        const std::string currentValuePath = _pathPrefix + ".ulPeakThroughput";
                
        

    }
         
    if (dlPeakThroughPutIsSet())
    {
        const std::string& value = m_DlPeakThroughPut;
        const std::string currentValuePath = _pathPrefix + ".dlPeakThroughPut";
                
        

    }
         
    if (ulAveragePacketThroughputIsSet())
    {
        const std::string& value = m_UlAveragePacketThroughput;
        const std::string currentValuePath = _pathPrefix + ".ulAveragePacketThroughput";
                
        

    }
         
    if (dlAveragePacketThroughputIsSet())
    {
        const std::string& value = m_DlAveragePacketThroughput;
        const std::string currentValuePath = _pathPrefix + ".dlAveragePacketThroughput";
                
        

    }
         
    if (ulPeakPacketThroughputIsSet())
    {
        const std::string& value = m_UlPeakPacketThroughput;
        const std::string currentValuePath = _pathPrefix + ".ulPeakPacketThroughput";
                
        

    }
         
    if (dlPeakPacketThroughputIsSet())
    {
        const std::string& value = m_DlPeakPacketThroughput;
        const std::string currentValuePath = _pathPrefix + ".dlPeakPacketThroughput";
                
        

    }
    
    return success;
}

bool ThroughputStatisticsMeasurement::operator==(const ThroughputStatisticsMeasurement& rhs) const
{
    return
    
    
    
    ((!ulAverageThroughputIsSet() && !rhs.ulAverageThroughputIsSet()) || (ulAverageThroughputIsSet() && rhs.ulAverageThroughputIsSet() && getUlAverageThroughput() == rhs.getUlAverageThroughput())) &&
    
    
    ((!dlAverageThroughputIsSet() && !rhs.dlAverageThroughputIsSet()) || (dlAverageThroughputIsSet() && rhs.dlAverageThroughputIsSet() && getDlAverageThroughput() == rhs.getDlAverageThroughput())) &&
    
    
    ((!ulPeakThroughputIsSet() && !rhs.ulPeakThroughputIsSet()) || (ulPeakThroughputIsSet() && rhs.ulPeakThroughputIsSet() && getUlPeakThroughput() == rhs.getUlPeakThroughput())) &&
    
    
    ((!dlPeakThroughPutIsSet() && !rhs.dlPeakThroughPutIsSet()) || (dlPeakThroughPutIsSet() && rhs.dlPeakThroughPutIsSet() && getDlPeakThroughPut() == rhs.getDlPeakThroughPut())) &&
    
    
    ((!ulAveragePacketThroughputIsSet() && !rhs.ulAveragePacketThroughputIsSet()) || (ulAveragePacketThroughputIsSet() && rhs.ulAveragePacketThroughputIsSet() && getUlAveragePacketThroughput() == rhs.getUlAveragePacketThroughput())) &&
    
    
    ((!dlAveragePacketThroughputIsSet() && !rhs.dlAveragePacketThroughputIsSet()) || (dlAveragePacketThroughputIsSet() && rhs.dlAveragePacketThroughputIsSet() && getDlAveragePacketThroughput() == rhs.getDlAveragePacketThroughput())) &&
    
    
    ((!ulPeakPacketThroughputIsSet() && !rhs.ulPeakPacketThroughputIsSet()) || (ulPeakPacketThroughputIsSet() && rhs.ulPeakPacketThroughputIsSet() && getUlPeakPacketThroughput() == rhs.getUlPeakPacketThroughput())) &&
    
    
    ((!dlPeakPacketThroughputIsSet() && !rhs.dlPeakPacketThroughputIsSet()) || (dlPeakPacketThroughputIsSet() && rhs.dlPeakPacketThroughputIsSet() && getDlPeakPacketThroughput() == rhs.getDlPeakPacketThroughput()))
    
    ;
}

bool ThroughputStatisticsMeasurement::operator!=(const ThroughputStatisticsMeasurement& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const ThroughputStatisticsMeasurement& o)
{
    j = nlohmann::json();
    if(o.ulAverageThroughputIsSet())
        j["ulAverageThroughput"] = o.m_UlAverageThroughput;
    if(o.dlAverageThroughputIsSet())
        j["dlAverageThroughput"] = o.m_DlAverageThroughput;
    if(o.ulPeakThroughputIsSet())
        j["ulPeakThroughput"] = o.m_UlPeakThroughput;
    if(o.dlPeakThroughPutIsSet())
        j["dlPeakThroughPut"] = o.m_DlPeakThroughPut;
    if(o.ulAveragePacketThroughputIsSet())
        j["ulAveragePacketThroughput"] = o.m_UlAveragePacketThroughput;
    if(o.dlAveragePacketThroughputIsSet())
        j["dlAveragePacketThroughput"] = o.m_DlAveragePacketThroughput;
    if(o.ulPeakPacketThroughputIsSet())
        j["ulPeakPacketThroughput"] = o.m_UlPeakPacketThroughput;
    if(o.dlPeakPacketThroughputIsSet())
        j["dlPeakPacketThroughput"] = o.m_DlPeakPacketThroughput;
    
}

void from_json(const nlohmann::json& j, ThroughputStatisticsMeasurement& o)
{
    if(j.find("ulAverageThroughput") != j.end())
    {
        j.at("ulAverageThroughput").get_to(o.m_UlAverageThroughput);
        o.m_UlAverageThroughputIsSet = true;
    } 
    if(j.find("dlAverageThroughput") != j.end())
    {
        j.at("dlAverageThroughput").get_to(o.m_DlAverageThroughput);
        o.m_DlAverageThroughputIsSet = true;
    } 
    if(j.find("ulPeakThroughput") != j.end())
    {
        j.at("ulPeakThroughput").get_to(o.m_UlPeakThroughput);
        o.m_UlPeakThroughputIsSet = true;
    } 
    if(j.find("dlPeakThroughPut") != j.end())
    {
        j.at("dlPeakThroughPut").get_to(o.m_DlPeakThroughPut);
        o.m_DlPeakThroughPutIsSet = true;
    } 
    if(j.find("ulAveragePacketThroughput") != j.end())
    {
        j.at("ulAveragePacketThroughput").get_to(o.m_UlAveragePacketThroughput);
        o.m_UlAveragePacketThroughputIsSet = true;
    } 
    if(j.find("dlAveragePacketThroughput") != j.end())
    {
        j.at("dlAveragePacketThroughput").get_to(o.m_DlAveragePacketThroughput);
        o.m_DlAveragePacketThroughputIsSet = true;
    } 
    if(j.find("ulPeakPacketThroughput") != j.end())
    {
        j.at("ulPeakPacketThroughput").get_to(o.m_UlPeakPacketThroughput);
        o.m_UlPeakPacketThroughputIsSet = true;
    } 
    if(j.find("dlPeakPacketThroughput") != j.end())
    {
        j.at("dlPeakPacketThroughput").get_to(o.m_DlPeakPacketThroughput);
        o.m_DlPeakPacketThroughputIsSet = true;
    } 
    
}

std::string ThroughputStatisticsMeasurement::getUlAverageThroughput() const
{
    return m_UlAverageThroughput;
}
void ThroughputStatisticsMeasurement::setUlAverageThroughput(std::string const& value)
{
    m_UlAverageThroughput = value;
    m_UlAverageThroughputIsSet = true;
}
bool ThroughputStatisticsMeasurement::ulAverageThroughputIsSet() const
{
    return m_UlAverageThroughputIsSet;
}
void ThroughputStatisticsMeasurement::unsetUlAverageThroughput()
{
    m_UlAverageThroughputIsSet = false;
}
std::string ThroughputStatisticsMeasurement::getDlAverageThroughput() const
{
    return m_DlAverageThroughput;
}
void ThroughputStatisticsMeasurement::setDlAverageThroughput(std::string const& value)
{
    m_DlAverageThroughput = value;
    m_DlAverageThroughputIsSet = true;
}
bool ThroughputStatisticsMeasurement::dlAverageThroughputIsSet() const
{
    return m_DlAverageThroughputIsSet;
}
void ThroughputStatisticsMeasurement::unsetDlAverageThroughput()
{
    m_DlAverageThroughputIsSet = false;
}
std::string ThroughputStatisticsMeasurement::getUlPeakThroughput() const
{
    return m_UlPeakThroughput;
}
void ThroughputStatisticsMeasurement::setUlPeakThroughput(std::string const& value)
{
    m_UlPeakThroughput = value;
    m_UlPeakThroughputIsSet = true;
}
bool ThroughputStatisticsMeasurement::ulPeakThroughputIsSet() const
{
    return m_UlPeakThroughputIsSet;
}
void ThroughputStatisticsMeasurement::unsetUlPeakThroughput()
{
    m_UlPeakThroughputIsSet = false;
}
std::string ThroughputStatisticsMeasurement::getDlPeakThroughPut() const
{
    return m_DlPeakThroughPut;
}
void ThroughputStatisticsMeasurement::setDlPeakThroughPut(std::string const& value)
{
    m_DlPeakThroughPut = value;
    m_DlPeakThroughPutIsSet = true;
}
bool ThroughputStatisticsMeasurement::dlPeakThroughPutIsSet() const
{
    return m_DlPeakThroughPutIsSet;
}
void ThroughputStatisticsMeasurement::unsetDlPeakThroughPut()
{
    m_DlPeakThroughPutIsSet = false;
}
std::string ThroughputStatisticsMeasurement::getUlAveragePacketThroughput() const
{
    return m_UlAveragePacketThroughput;
}
void ThroughputStatisticsMeasurement::setUlAveragePacketThroughput(std::string const& value)
{
    m_UlAveragePacketThroughput = value;
    m_UlAveragePacketThroughputIsSet = true;
}
bool ThroughputStatisticsMeasurement::ulAveragePacketThroughputIsSet() const
{
    return m_UlAveragePacketThroughputIsSet;
}
void ThroughputStatisticsMeasurement::unsetUlAveragePacketThroughput()
{
    m_UlAveragePacketThroughputIsSet = false;
}
std::string ThroughputStatisticsMeasurement::getDlAveragePacketThroughput() const
{
    return m_DlAveragePacketThroughput;
}
void ThroughputStatisticsMeasurement::setDlAveragePacketThroughput(std::string const& value)
{
    m_DlAveragePacketThroughput = value;
    m_DlAveragePacketThroughputIsSet = true;
}
bool ThroughputStatisticsMeasurement::dlAveragePacketThroughputIsSet() const
{
    return m_DlAveragePacketThroughputIsSet;
}
void ThroughputStatisticsMeasurement::unsetDlAveragePacketThroughput()
{
    m_DlAveragePacketThroughputIsSet = false;
}
std::string ThroughputStatisticsMeasurement::getUlPeakPacketThroughput() const
{
    return m_UlPeakPacketThroughput;
}
void ThroughputStatisticsMeasurement::setUlPeakPacketThroughput(std::string const& value)
{
    m_UlPeakPacketThroughput = value;
    m_UlPeakPacketThroughputIsSet = true;
}
bool ThroughputStatisticsMeasurement::ulPeakPacketThroughputIsSet() const
{
    return m_UlPeakPacketThroughputIsSet;
}
void ThroughputStatisticsMeasurement::unsetUlPeakPacketThroughput()
{
    m_UlPeakPacketThroughputIsSet = false;
}
std::string ThroughputStatisticsMeasurement::getDlPeakPacketThroughput() const
{
    return m_DlPeakPacketThroughput;
}
void ThroughputStatisticsMeasurement::setDlPeakPacketThroughput(std::string const& value)
{
    m_DlPeakPacketThroughput = value;
    m_DlPeakPacketThroughputIsSet = true;
}
bool ThroughputStatisticsMeasurement::dlPeakPacketThroughputIsSet() const
{
    return m_DlPeakPacketThroughputIsSet;
}
void ThroughputStatisticsMeasurement::unsetDlPeakPacketThroughput()
{
    m_DlPeakPacketThroughputIsSet = false;
}


} // namespace org::openapitools::server::model

