/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ThroughputMeasurement.h
 *
 * Throughput Measurement information
 */

#ifndef ThroughputMeasurement_H_
#define ThroughputMeasurement_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Throughput Measurement information
/// </summary>
class  ThroughputMeasurement
{
public:
    ThroughputMeasurement();
    virtual ~ThroughputMeasurement() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const ThroughputMeasurement& rhs) const;
    bool operator!=(const ThroughputMeasurement& rhs) const;

    /////////////////////////////////////////////
    /// ThroughputMeasurement members

    /// <summary>
    /// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \&quot;K\&quot; is used to represent the standard symbol \&quot;k\&quot;. 
    /// </summary>
    std::string getUlThroughput() const;
    void setUlThroughput(std::string const& value);
    bool ulThroughputIsSet() const;
    void unsetUlThroughput();
    /// <summary>
    /// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \&quot;K\&quot; is used to represent the standard symbol \&quot;k\&quot;. 
    /// </summary>
    std::string getDlThroughput() const;
    void setDlThroughput(std::string const& value);
    bool dlThroughputIsSet() const;
    void unsetDlThroughput();
    /// <summary>
    /// String representing a packet rate, i.e., packet per second; the prefixes follow the symbols from The International System of Units, and represent x1000 multipliers. 
    /// </summary>
    std::string getUlPacketThroughput() const;
    void setUlPacketThroughput(std::string const& value);
    bool ulPacketThroughputIsSet() const;
    void unsetUlPacketThroughput();
    /// <summary>
    /// String representing a packet rate, i.e., packet per second; the prefixes follow the symbols from The International System of Units, and represent x1000 multipliers. 
    /// </summary>
    std::string getDlPacketThroughput() const;
    void setDlPacketThroughput(std::string const& value);
    bool dlPacketThroughputIsSet() const;
    void unsetDlPacketThroughput();

    friend  void to_json(nlohmann::json& j, const ThroughputMeasurement& o);
    friend  void from_json(const nlohmann::json& j, ThroughputMeasurement& o);
protected:
    std::string m_UlThroughput;
    bool m_UlThroughputIsSet;
    std::string m_DlThroughput;
    bool m_DlThroughputIsSet;
    std::string m_UlPacketThroughput;
    bool m_UlPacketThroughputIsSet;
    std::string m_DlPacketThroughput;
    bool m_DlPacketThroughputIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* ThroughputMeasurement_H_ */
