/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "ThroughputMeasurement.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

ThroughputMeasurement::ThroughputMeasurement()
{
    m_UlThroughput = "";
    m_UlThroughputIsSet = false;
    m_DlThroughput = "";
    m_DlThroughputIsSet = false;
    m_UlPacketThroughput = "";
    m_UlPacketThroughputIsSet = false;
    m_DlPacketThroughput = "";
    m_DlPacketThroughputIsSet = false;
    
}

void ThroughputMeasurement::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool ThroughputMeasurement::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool ThroughputMeasurement::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "ThroughputMeasurement" : pathPrefix;

         
    if (ulThroughputIsSet())
    {
        const std::string& value = m_UlThroughput;
        const std::string currentValuePath = _pathPrefix + ".ulThroughput";
                
        

    }
         
    if (dlThroughputIsSet())
    {
        const std::string& value = m_DlThroughput;
        const std::string currentValuePath = _pathPrefix + ".dlThroughput";
                
        

    }
         
    if (ulPacketThroughputIsSet())
    {
        const std::string& value = m_UlPacketThroughput;
        const std::string currentValuePath = _pathPrefix + ".ulPacketThroughput";
                
        

    }
         
    if (dlPacketThroughputIsSet())
    {
        const std::string& value = m_DlPacketThroughput;
        const std::string currentValuePath = _pathPrefix + ".dlPacketThroughput";
                
        

    }
    
    return success;
}

bool ThroughputMeasurement::operator==(const ThroughputMeasurement& rhs) const
{
    return
    
    
    
    ((!ulThroughputIsSet() && !rhs.ulThroughputIsSet()) || (ulThroughputIsSet() && rhs.ulThroughputIsSet() && getUlThroughput() == rhs.getUlThroughput())) &&
    
    
    ((!dlThroughputIsSet() && !rhs.dlThroughputIsSet()) || (dlThroughputIsSet() && rhs.dlThroughputIsSet() && getDlThroughput() == rhs.getDlThroughput())) &&
    
    
    ((!ulPacketThroughputIsSet() && !rhs.ulPacketThroughputIsSet()) || (ulPacketThroughputIsSet() && rhs.ulPacketThroughputIsSet() && getUlPacketThroughput() == rhs.getUlPacketThroughput())) &&
    
    
    ((!dlPacketThroughputIsSet() && !rhs.dlPacketThroughputIsSet()) || (dlPacketThroughputIsSet() && rhs.dlPacketThroughputIsSet() && getDlPacketThroughput() == rhs.getDlPacketThroughput()))
    
    ;
}

bool ThroughputMeasurement::operator!=(const ThroughputMeasurement& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const ThroughputMeasurement& o)
{
    j = nlohmann::json();
    if(o.ulThroughputIsSet())
        j["ulThroughput"] = o.m_UlThroughput;
    if(o.dlThroughputIsSet())
        j["dlThroughput"] = o.m_DlThroughput;
    if(o.ulPacketThroughputIsSet())
        j["ulPacketThroughput"] = o.m_UlPacketThroughput;
    if(o.dlPacketThroughputIsSet())
        j["dlPacketThroughput"] = o.m_DlPacketThroughput;
    
}

void from_json(const nlohmann::json& j, ThroughputMeasurement& o)
{
    if(j.find("ulThroughput") != j.end())
    {
        j.at("ulThroughput").get_to(o.m_UlThroughput);
        o.m_UlThroughputIsSet = true;
    } 
    if(j.find("dlThroughput") != j.end())
    {
        j.at("dlThroughput").get_to(o.m_DlThroughput);
        o.m_DlThroughputIsSet = true;
    } 
    if(j.find("ulPacketThroughput") != j.end())
    {
        j.at("ulPacketThroughput").get_to(o.m_UlPacketThroughput);
        o.m_UlPacketThroughputIsSet = true;
    } 
    if(j.find("dlPacketThroughput") != j.end())
    {
        j.at("dlPacketThroughput").get_to(o.m_DlPacketThroughput);
        o.m_DlPacketThroughputIsSet = true;
    } 
    
}

std::string ThroughputMeasurement::getUlThroughput() const
{
    return m_UlThroughput;
}
void ThroughputMeasurement::setUlThroughput(std::string const& value)
{
    m_UlThroughput = value;
    m_UlThroughputIsSet = true;
}
bool ThroughputMeasurement::ulThroughputIsSet() const
{
    return m_UlThroughputIsSet;
}
void ThroughputMeasurement::unsetUlThroughput()
{
    m_UlThroughputIsSet = false;
}
std::string ThroughputMeasurement::getDlThroughput() const
{
    return m_DlThroughput;
}
void ThroughputMeasurement::setDlThroughput(std::string const& value)
{
    m_DlThroughput = value;
    m_DlThroughputIsSet = true;
}
bool ThroughputMeasurement::dlThroughputIsSet() const
{
    return m_DlThroughputIsSet;
}
void ThroughputMeasurement::unsetDlThroughput()
{
    m_DlThroughputIsSet = false;
}
std::string ThroughputMeasurement::getUlPacketThroughput() const
{
    return m_UlPacketThroughput;
}
void ThroughputMeasurement::setUlPacketThroughput(std::string const& value)
{
    m_UlPacketThroughput = value;
    m_UlPacketThroughputIsSet = true;
}
bool ThroughputMeasurement::ulPacketThroughputIsSet() const
{
    return m_UlPacketThroughputIsSet;
}
void ThroughputMeasurement::unsetUlPacketThroughput()
{
    m_UlPacketThroughputIsSet = false;
}
std::string ThroughputMeasurement::getDlPacketThroughput() const
{
    return m_DlPacketThroughput;
}
void ThroughputMeasurement::setDlPacketThroughput(std::string const& value)
{
    m_DlPacketThroughput = value;
    m_DlPacketThroughputIsSet = true;
}
bool ThroughputMeasurement::dlPacketThroughputIsSet() const
{
    return m_DlPacketThroughputIsSet;
}
void ThroughputMeasurement::unsetDlPacketThroughput()
{
    m_DlPacketThroughputIsSet = false;
}


} // namespace org::openapitools::server::model

