/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ThroughputStatisticsMeasurement.h
 *
 * Throughput Statistics Measurement
 */

#ifndef ThroughputStatisticsMeasurement_H_
#define ThroughputStatisticsMeasurement_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Throughput Statistics Measurement
/// </summary>
class  ThroughputStatisticsMeasurement
{
public:
    ThroughputStatisticsMeasurement();
    virtual ~ThroughputStatisticsMeasurement() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const ThroughputStatisticsMeasurement& rhs) const;
    bool operator!=(const ThroughputStatisticsMeasurement& rhs) const;

    /////////////////////////////////////////////
    /// ThroughputStatisticsMeasurement members

    /// <summary>
    /// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \&quot;K\&quot; is used to represent the standard symbol \&quot;k\&quot;. 
    /// </summary>
    std::string getUlAverageThroughput() const;
    void setUlAverageThroughput(std::string const& value);
    bool ulAverageThroughputIsSet() const;
    void unsetUlAverageThroughput();
    /// <summary>
    /// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \&quot;K\&quot; is used to represent the standard symbol \&quot;k\&quot;. 
    /// </summary>
    std::string getDlAverageThroughput() const;
    void setDlAverageThroughput(std::string const& value);
    bool dlAverageThroughputIsSet() const;
    void unsetDlAverageThroughput();
    /// <summary>
    /// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \&quot;K\&quot; is used to represent the standard symbol \&quot;k\&quot;. 
    /// </summary>
    std::string getUlPeakThroughput() const;
    void setUlPeakThroughput(std::string const& value);
    bool ulPeakThroughputIsSet() const;
    void unsetUlPeakThroughput();
    /// <summary>
    /// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \&quot;K\&quot; is used to represent the standard symbol \&quot;k\&quot;. 
    /// </summary>
    std::string getDlPeakThroughPut() const;
    void setDlPeakThroughPut(std::string const& value);
    bool dlPeakThroughPutIsSet() const;
    void unsetDlPeakThroughPut();
    /// <summary>
    /// String representing a packet rate, i.e., packet per second; the prefixes follow the symbols from The International System of Units, and represent x1000 multipliers. 
    /// </summary>
    std::string getUlAveragePacketThroughput() const;
    void setUlAveragePacketThroughput(std::string const& value);
    bool ulAveragePacketThroughputIsSet() const;
    void unsetUlAveragePacketThroughput();
    /// <summary>
    /// String representing a packet rate, i.e., packet per second; the prefixes follow the symbols from The International System of Units, and represent x1000 multipliers. 
    /// </summary>
    std::string getDlAveragePacketThroughput() const;
    void setDlAveragePacketThroughput(std::string const& value);
    bool dlAveragePacketThroughputIsSet() const;
    void unsetDlAveragePacketThroughput();
    /// <summary>
    /// String representing a packet rate, i.e., packet per second; the prefixes follow the symbols from The International System of Units, and represent x1000 multipliers. 
    /// </summary>
    std::string getUlPeakPacketThroughput() const;
    void setUlPeakPacketThroughput(std::string const& value);
    bool ulPeakPacketThroughputIsSet() const;
    void unsetUlPeakPacketThroughput();
    /// <summary>
    /// String representing a packet rate, i.e., packet per second; the prefixes follow the symbols from The International System of Units, and represent x1000 multipliers. 
    /// </summary>
    std::string getDlPeakPacketThroughput() const;
    void setDlPeakPacketThroughput(std::string const& value);
    bool dlPeakPacketThroughputIsSet() const;
    void unsetDlPeakPacketThroughput();

    friend  void to_json(nlohmann::json& j, const ThroughputStatisticsMeasurement& o);
    friend  void from_json(const nlohmann::json& j, ThroughputStatisticsMeasurement& o);
protected:
    std::string m_UlAverageThroughput;
    bool m_UlAverageThroughputIsSet;
    std::string m_DlAverageThroughput;
    bool m_DlAverageThroughputIsSet;
    std::string m_UlPeakThroughput;
    bool m_UlPeakThroughputIsSet;
    std::string m_DlPeakThroughPut;
    bool m_DlPeakThroughPutIsSet;
    std::string m_UlAveragePacketThroughput;
    bool m_UlAveragePacketThroughputIsSet;
    std::string m_DlAveragePacketThroughput;
    bool m_DlAveragePacketThroughputIsSet;
    std::string m_UlPeakPacketThroughput;
    bool m_UlPeakPacketThroughputIsSet;
    std::string m_DlPeakPacketThroughput;
    bool m_DlPeakPacketThroughputIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* ThroughputStatisticsMeasurement_H_ */
