/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "TscManagementInfo.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

TscManagementInfo::TscManagementInfo()
{
    m_PmicsIsSet = false;
    m_UmicIsSet = false;
    
}

void TscManagementInfo::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool TscManagementInfo::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool TscManagementInfo::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "TscManagementInfo" : pathPrefix;

         
    if (pmicsIsSet())
    {
        const std::vector<org::openapitools::server::model::PortManagementContainer>& value = m_Pmics;
        const std::string currentValuePath = _pathPrefix + ".pmics";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const org::openapitools::server::model::PortManagementContainer& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".pmics") && success;
 
                i++;
            }
        }

    }
        
    return success;
}

bool TscManagementInfo::operator==(const TscManagementInfo& rhs) const
{
    return
    
    
    
    ((!pmicsIsSet() && !rhs.pmicsIsSet()) || (pmicsIsSet() && rhs.pmicsIsSet() && getPmics() == rhs.getPmics())) &&
    
    
    ((!umicIsSet() && !rhs.umicIsSet()) || (umicIsSet() && rhs.umicIsSet() && getUmic() == rhs.getUmic()))
    
    ;
}

bool TscManagementInfo::operator!=(const TscManagementInfo& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const TscManagementInfo& o)
{
    j = nlohmann::json();
    if(o.pmicsIsSet() || !o.m_Pmics.empty())
        j["pmics"] = o.m_Pmics;
    if(o.umicIsSet())
        j["umic"] = o.m_Umic;
    
}

void from_json(const nlohmann::json& j, TscManagementInfo& o)
{
    if(j.find("pmics") != j.end())
    {
        j.at("pmics").get_to(o.m_Pmics);
        o.m_PmicsIsSet = true;
    } 
    if(j.find("umic") != j.end())
    {
        j.at("umic").get_to(o.m_Umic);
        o.m_UmicIsSet = true;
    } 
    
}

std::vector<org::openapitools::server::model::PortManagementContainer> TscManagementInfo::getPmics() const
{
    return m_Pmics;
}
void TscManagementInfo::setPmics(std::vector<org::openapitools::server::model::PortManagementContainer> const& value)
{
    m_Pmics = value;
    m_PmicsIsSet = true;
}
bool TscManagementInfo::pmicsIsSet() const
{
    return m_PmicsIsSet;
}
void TscManagementInfo::unsetPmics()
{
    m_PmicsIsSet = false;
}
org::openapitools::server::model::BridgeManagementContainer TscManagementInfo::getUmic() const
{
    return m_Umic;
}
void TscManagementInfo::setUmic(org::openapitools::server::model::BridgeManagementContainer const& value)
{
    m_Umic = value;
    m_UmicIsSet = true;
}
bool TscManagementInfo::umicIsSet() const
{
    return m_UmicIsSet;
}
void TscManagementInfo::unsetUmic()
{
    m_UmicIsSet = false;
}


} // namespace org::openapitools::server::model

