/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * TscManagementInfo.h
 *
 * TSC Management Information
 */

#ifndef TscManagementInfo_H_
#define TscManagementInfo_H_


#include "PortManagementContainer.h"
#include "BridgeManagementContainer.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// TSC Management Information
/// </summary>
class  TscManagementInfo
{
public:
    TscManagementInfo();
    virtual ~TscManagementInfo() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const TscManagementInfo& rhs) const;
    bool operator!=(const TscManagementInfo& rhs) const;

    /////////////////////////////////////////////
    /// TscManagementInfo members

    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::PortManagementContainer> getPmics() const;
    void setPmics(std::vector<org::openapitools::server::model::PortManagementContainer> const& value);
    bool pmicsIsSet() const;
    void unsetPmics();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::BridgeManagementContainer getUmic() const;
    void setUmic(org::openapitools::server::model::BridgeManagementContainer const& value);
    bool umicIsSet() const;
    void unsetUmic();

    friend  void to_json(nlohmann::json& j, const TscManagementInfo& o);
    friend  void from_json(const nlohmann::json& j, TscManagementInfo& o);
protected:
    std::vector<org::openapitools::server::model::PortManagementContainer> m_Pmics;
    bool m_PmicsIsSet;
    org::openapitools::server::model::BridgeManagementContainer m_Umic;
    bool m_UmicIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* TscManagementInfo_H_ */
