/**
* UPF GET Private UE IP address Service
* Nupf_GetPrivateUEIPaddr Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.0.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "UeIpInfo.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

UeIpInfo::UeIpInfo()
{
    m_PrivateIpv4Address = "";
    m_PrivateIpv4AddressIsSet = false;
    m_IpDomain = "";
    m_IpDomainIsSet = false;
    m_PrivateIpv6PrefixIsSet = false;
    m_PublicIpv4Address = "";
    m_PublicIpv4AddressIsSet = false;
    m_PublicIpv6PrefixIsSet = false;
    m_PortNumber = 0;
    m_PortNumberIsSet = false;
    m_Dnn = "";
    m_DnnIsSet = false;
    m_SnssaiIsSet = false;
    m_Supi = "";
    m_SupiIsSet = false;
    
}

void UeIpInfo::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool UeIpInfo::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool UeIpInfo::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "UeIpInfo" : pathPrefix;

         
    if (privateIpv4AddressIsSet())
    {
        const std::string& value = m_PrivateIpv4Address;
        const std::string currentValuePath = _pathPrefix + ".privateIpv4Address";
                
        

    }
                 
    if (publicIpv4AddressIsSet())
    {
        const std::string& value = m_PublicIpv4Address;
        const std::string currentValuePath = _pathPrefix + ".publicIpv4Address";
                
        

    }
             
    if (portNumberIsSet())
    {
        const int32_t& value = m_PortNumber;
        const std::string currentValuePath = _pathPrefix + ".portNumber";
                
        
        if (value < 0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0;";
        }
        if (value > 65535)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 65535;";
        }

    }
                 
    if (supiIsSet())
    {
        const std::string& value = m_Supi;
        const std::string currentValuePath = _pathPrefix + ".supi";
                
        

    }
    
    return success;
}

bool UeIpInfo::operator==(const UeIpInfo& rhs) const
{
    return
    
    
    
    ((!privateIpv4AddressIsSet() && !rhs.privateIpv4AddressIsSet()) || (privateIpv4AddressIsSet() && rhs.privateIpv4AddressIsSet() && getPrivateIpv4Address() == rhs.getPrivateIpv4Address())) &&
    
    
    ((!ipDomainIsSet() && !rhs.ipDomainIsSet()) || (ipDomainIsSet() && rhs.ipDomainIsSet() && getIpDomain() == rhs.getIpDomain())) &&
    
    
    ((!privateIpv6PrefixIsSet() && !rhs.privateIpv6PrefixIsSet()) || (privateIpv6PrefixIsSet() && rhs.privateIpv6PrefixIsSet() && getPrivateIpv6Prefix() == rhs.getPrivateIpv6Prefix())) &&
    
    
    ((!publicIpv4AddressIsSet() && !rhs.publicIpv4AddressIsSet()) || (publicIpv4AddressIsSet() && rhs.publicIpv4AddressIsSet() && getPublicIpv4Address() == rhs.getPublicIpv4Address())) &&
    
    
    ((!publicIpv6PrefixIsSet() && !rhs.publicIpv6PrefixIsSet()) || (publicIpv6PrefixIsSet() && rhs.publicIpv6PrefixIsSet() && getPublicIpv6Prefix() == rhs.getPublicIpv6Prefix())) &&
    
    
    ((!portNumberIsSet() && !rhs.portNumberIsSet()) || (portNumberIsSet() && rhs.portNumberIsSet() && getPortNumber() == rhs.getPortNumber())) &&
    
    
    ((!dnnIsSet() && !rhs.dnnIsSet()) || (dnnIsSet() && rhs.dnnIsSet() && getDnn() == rhs.getDnn())) &&
    
    
    ((!snssaiIsSet() && !rhs.snssaiIsSet()) || (snssaiIsSet() && rhs.snssaiIsSet() && getSnssai() == rhs.getSnssai())) &&
    
    
    ((!supiIsSet() && !rhs.supiIsSet()) || (supiIsSet() && rhs.supiIsSet() && getSupi() == rhs.getSupi()))
    
    ;
}

bool UeIpInfo::operator!=(const UeIpInfo& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const UeIpInfo& o)
{
    j = nlohmann::json();
    if(o.privateIpv4AddressIsSet())
        j["privateIpv4Address"] = o.m_PrivateIpv4Address;
    if(o.ipDomainIsSet())
        j["ipDomain"] = o.m_IpDomain;
    if(o.privateIpv6PrefixIsSet())
        j["privateIpv6Prefix"] = o.m_PrivateIpv6Prefix;
    if(o.publicIpv4AddressIsSet())
        j["publicIpv4Address"] = o.m_PublicIpv4Address;
    if(o.publicIpv6PrefixIsSet())
        j["publicIpv6Prefix"] = o.m_PublicIpv6Prefix;
    if(o.portNumberIsSet())
        j["portNumber"] = o.m_PortNumber;
    if(o.dnnIsSet())
        j["dnn"] = o.m_Dnn;
    if(o.snssaiIsSet())
        j["snssai"] = o.m_Snssai;
    if(o.supiIsSet())
        j["supi"] = o.m_Supi;
    
}

void from_json(const nlohmann::json& j, UeIpInfo& o)
{
    if(j.find("privateIpv4Address") != j.end())
    {
        j.at("privateIpv4Address").get_to(o.m_PrivateIpv4Address);
        o.m_PrivateIpv4AddressIsSet = true;
    } 
    if(j.find("ipDomain") != j.end())
    {
        j.at("ipDomain").get_to(o.m_IpDomain);
        o.m_IpDomainIsSet = true;
    } 
    if(j.find("privateIpv6Prefix") != j.end())
    {
        j.at("privateIpv6Prefix").get_to(o.m_PrivateIpv6Prefix);
        o.m_PrivateIpv6PrefixIsSet = true;
    } 
    if(j.find("publicIpv4Address") != j.end())
    {
        j.at("publicIpv4Address").get_to(o.m_PublicIpv4Address);
        o.m_PublicIpv4AddressIsSet = true;
    } 
    if(j.find("publicIpv6Prefix") != j.end())
    {
        j.at("publicIpv6Prefix").get_to(o.m_PublicIpv6Prefix);
        o.m_PublicIpv6PrefixIsSet = true;
    } 
    if(j.find("portNumber") != j.end())
    {
        j.at("portNumber").get_to(o.m_PortNumber);
        o.m_PortNumberIsSet = true;
    } 
    if(j.find("dnn") != j.end())
    {
        j.at("dnn").get_to(o.m_Dnn);
        o.m_DnnIsSet = true;
    } 
    if(j.find("snssai") != j.end())
    {
        j.at("snssai").get_to(o.m_Snssai);
        o.m_SnssaiIsSet = true;
    } 
    if(j.find("supi") != j.end())
    {
        j.at("supi").get_to(o.m_Supi);
        o.m_SupiIsSet = true;
    } 
    
}

std::string UeIpInfo::getPrivateIpv4Address() const
{
    return m_PrivateIpv4Address;
}
void UeIpInfo::setPrivateIpv4Address(std::string const& value)
{
    m_PrivateIpv4Address = value;
    m_PrivateIpv4AddressIsSet = true;
}
bool UeIpInfo::privateIpv4AddressIsSet() const
{
    return m_PrivateIpv4AddressIsSet;
}
void UeIpInfo::unsetPrivateIpv4Address()
{
    m_PrivateIpv4AddressIsSet = false;
}
std::string UeIpInfo::getIpDomain() const
{
    return m_IpDomain;
}
void UeIpInfo::setIpDomain(std::string const& value)
{
    m_IpDomain = value;
    m_IpDomainIsSet = true;
}
bool UeIpInfo::ipDomainIsSet() const
{
    return m_IpDomainIsSet;
}
void UeIpInfo::unsetIpDomain()
{
    m_IpDomainIsSet = false;
}
org::openapitools::server::model::Ipv6Prefix UeIpInfo::getPrivateIpv6Prefix() const
{
    return m_PrivateIpv6Prefix;
}
void UeIpInfo::setPrivateIpv6Prefix(org::openapitools::server::model::Ipv6Prefix const& value)
{
    m_PrivateIpv6Prefix = value;
    m_PrivateIpv6PrefixIsSet = true;
}
bool UeIpInfo::privateIpv6PrefixIsSet() const
{
    return m_PrivateIpv6PrefixIsSet;
}
void UeIpInfo::unsetPrivateIpv6Prefix()
{
    m_PrivateIpv6PrefixIsSet = false;
}
std::string UeIpInfo::getPublicIpv4Address() const
{
    return m_PublicIpv4Address;
}
void UeIpInfo::setPublicIpv4Address(std::string const& value)
{
    m_PublicIpv4Address = value;
    m_PublicIpv4AddressIsSet = true;
}
bool UeIpInfo::publicIpv4AddressIsSet() const
{
    return m_PublicIpv4AddressIsSet;
}
void UeIpInfo::unsetPublicIpv4Address()
{
    m_PublicIpv4AddressIsSet = false;
}
org::openapitools::server::model::Ipv6Prefix UeIpInfo::getPublicIpv6Prefix() const
{
    return m_PublicIpv6Prefix;
}
void UeIpInfo::setPublicIpv6Prefix(org::openapitools::server::model::Ipv6Prefix const& value)
{
    m_PublicIpv6Prefix = value;
    m_PublicIpv6PrefixIsSet = true;
}
bool UeIpInfo::publicIpv6PrefixIsSet() const
{
    return m_PublicIpv6PrefixIsSet;
}
void UeIpInfo::unsetPublicIpv6Prefix()
{
    m_PublicIpv6PrefixIsSet = false;
}
int32_t UeIpInfo::getPortNumber() const
{
    return m_PortNumber;
}
void UeIpInfo::setPortNumber(int32_t const value)
{
    m_PortNumber = value;
    m_PortNumberIsSet = true;
}
bool UeIpInfo::portNumberIsSet() const
{
    return m_PortNumberIsSet;
}
void UeIpInfo::unsetPortNumber()
{
    m_PortNumberIsSet = false;
}
std::string UeIpInfo::getDnn() const
{
    return m_Dnn;
}
void UeIpInfo::setDnn(std::string const& value)
{
    m_Dnn = value;
    m_DnnIsSet = true;
}
bool UeIpInfo::dnnIsSet() const
{
    return m_DnnIsSet;
}
void UeIpInfo::unsetDnn()
{
    m_DnnIsSet = false;
}
org::openapitools::server::model::Snssai UeIpInfo::getSnssai() const
{
    return m_Snssai;
}
void UeIpInfo::setSnssai(org::openapitools::server::model::Snssai const& value)
{
    m_Snssai = value;
    m_SnssaiIsSet = true;
}
bool UeIpInfo::snssaiIsSet() const
{
    return m_SnssaiIsSet;
}
void UeIpInfo::unsetSnssai()
{
    m_SnssaiIsSet = false;
}
std::string UeIpInfo::getSupi() const
{
    return m_Supi;
}
void UeIpInfo::setSupi(std::string const& value)
{
    m_Supi = value;
    m_SupiIsSet = true;
}
bool UeIpInfo::supiIsSet() const
{
    return m_SupiIsSet;
}
void UeIpInfo::unsetSupi()
{
    m_SupiIsSet = false;
}


} // namespace org::openapitools::server::model

