/**
* UPF GET Private UE IP address Service
* Nupf_GetPrivateUEIPaddr Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.0.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UeIpInfo.h
 *
 * a UE IP Address Info for a PDU session
 */

#ifndef UeIpInfo_H_
#define UeIpInfo_H_


#include <string>
#include "Ipv6Prefix.h"
#include "Snssai.h"
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// a UE IP Address Info for a PDU session
/// </summary>
class  UeIpInfo
{
public:
    UeIpInfo();
    virtual ~UeIpInfo() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const UeIpInfo& rhs) const;
    bool operator!=(const UeIpInfo& rhs) const;

    /////////////////////////////////////////////
    /// UeIpInfo members

    /// <summary>
    /// String identifying a IPv4 address formatted in the &#39;dotted decimal&#39; notation as defined in RFC 1166. 
    /// </summary>
    std::string getPrivateIpv4Address() const;
    void setPrivateIpv4Address(std::string const& value);
    bool privateIpv4AddressIsSet() const;
    void unsetPrivateIpv4Address();
    /// <summary>
    /// 
    /// </summary>
    std::string getIpDomain() const;
    void setIpDomain(std::string const& value);
    bool ipDomainIsSet() const;
    void unsetIpDomain();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::Ipv6Prefix getPrivateIpv6Prefix() const;
    void setPrivateIpv6Prefix(org::openapitools::server::model::Ipv6Prefix const& value);
    bool privateIpv6PrefixIsSet() const;
    void unsetPrivateIpv6Prefix();
    /// <summary>
    /// String identifying a IPv4 address formatted in the &#39;dotted decimal&#39; notation as defined in RFC 1166. 
    /// </summary>
    std::string getPublicIpv4Address() const;
    void setPublicIpv4Address(std::string const& value);
    bool publicIpv4AddressIsSet() const;
    void unsetPublicIpv4Address();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::Ipv6Prefix getPublicIpv6Prefix() const;
    void setPublicIpv6Prefix(org::openapitools::server::model::Ipv6Prefix const& value);
    bool publicIpv6PrefixIsSet() const;
    void unsetPublicIpv6Prefix();
    /// <summary>
    /// Integer where the allowed values correspond to the value range of an unsigned 16-bit integer.
    /// </summary>
    int32_t getPortNumber() const;
    void setPortNumber(int32_t const value);
    bool portNumberIsSet() const;
    void unsetPortNumber();
    /// <summary>
    /// String representing a Data Network as defined in clause 9A of 3GPP TS 23.003;  it shall contain either a DNN Network Identifier, or a full DNN with both the Network  Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots  (e.g. \&quot;Label1.Label2.Label3\&quot;). 
    /// </summary>
    std::string getDnn() const;
    void setDnn(std::string const& value);
    bool dnnIsSet() const;
    void unsetDnn();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::Snssai getSnssai() const;
    void setSnssai(org::openapitools::server::model::Snssai const& value);
    bool snssaiIsSet() const;
    void unsetSnssai();
    /// <summary>
    /// String identifying a Supi that shall contain either an IMSI, a network specific identifier, a Global Cable Identifier (GCI) or a Global Line Identifier (GLI) as specified in clause  2.2A of 3GPP TS 23.003. It shall be formatted as follows  - for an IMSI \&quot;imsi-&lt;imsi&gt;\&quot;, where &lt;imsi&gt; shall be formatted according to clause 2.2    of 3GPP TS 23.003 that describes an IMSI.  - for a network specific identifier \&quot;nai-&lt;nai&gt;, where &lt;nai&gt; shall be formatted    according to clause 28.7.2 of 3GPP TS 23.003 that describes an NAI.  - for a GCI \&quot;gci-&lt;gci&gt;\&quot;, where &lt;gci&gt; shall be formatted according to clause 28.15.2    of 3GPP TS 23.003.  - for a GLI \&quot;gli-&lt;gli&gt;\&quot;, where &lt;gli&gt; shall be formatted according to clause 28.16.2 of    3GPP TS 23.003.To enable that the value is used as part of an URI, the string shall    only contain characters allowed according to the \&quot;lower-with-hyphen\&quot; naming convention    defined in 3GPP TS 29.501. 
    /// </summary>
    std::string getSupi() const;
    void setSupi(std::string const& value);
    bool supiIsSet() const;
    void unsetSupi();

    friend  void to_json(nlohmann::json& j, const UeIpInfo& o);
    friend  void from_json(const nlohmann::json& j, UeIpInfo& o);
protected:
    std::string m_PrivateIpv4Address;
    bool m_PrivateIpv4AddressIsSet;
    std::string m_IpDomain;
    bool m_IpDomainIsSet;
    org::openapitools::server::model::Ipv6Prefix m_PrivateIpv6Prefix;
    bool m_PrivateIpv6PrefixIsSet;
    std::string m_PublicIpv4Address;
    bool m_PublicIpv4AddressIsSet;
    org::openapitools::server::model::Ipv6Prefix m_PublicIpv6Prefix;
    bool m_PublicIpv6PrefixIsSet;
    int32_t m_PortNumber;
    bool m_PortNumberIsSet;
    std::string m_Dnn;
    bool m_DnnIsSet;
    org::openapitools::server::model::Snssai m_Snssai;
    bool m_SnssaiIsSet;
    std::string m_Supi;
    bool m_SupiIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* UeIpInfo_H_ */
