/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "UpfEventMode.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

UpfEventMode::UpfEventMode()
{
    m_MaxReports = 0;
    m_MaxReportsIsSet = false;
    m_Expiry = "";
    m_ExpiryIsSet = false;
    m_RepPeriod = 0;
    m_RepPeriodIsSet = false;
    m_SampRatio = 0;
    m_SampRatioIsSet = false;
    m_PartitioningCriteriaIsSet = false;
    m_NotifFlagIsSet = false;
    
}

void UpfEventMode::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool UpfEventMode::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool UpfEventMode::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "UpfEventMode" : pathPrefix;

                         
    if (sampRatioIsSet())
    {
        const int32_t& value = m_SampRatio;
        const std::string currentValuePath = _pathPrefix + ".sampRatio";
                
        
        if (value < 1)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 1;";
        }
        if (value > 100)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 100;";
        }

    }
         
    if (partitioningCriteriaIsSet())
    {
        const std::vector<org::openapitools::server::model::PartitioningCriteria>& value = m_PartitioningCriteria;
        const std::string currentValuePath = _pathPrefix + ".partitioningCriteria";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const org::openapitools::server::model::PartitioningCriteria& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".partitioningCriteria") && success;
 
                i++;
            }
        }

    }
        
    return success;
}

bool UpfEventMode::operator==(const UpfEventMode& rhs) const
{
    return
    
    
    (getTrigger() == rhs.getTrigger())
     &&
    
    
    ((!maxReportsIsSet() && !rhs.maxReportsIsSet()) || (maxReportsIsSet() && rhs.maxReportsIsSet() && getMaxReports() == rhs.getMaxReports())) &&
    
    
    ((!expiryIsSet() && !rhs.expiryIsSet()) || (expiryIsSet() && rhs.expiryIsSet() && getExpiry() == rhs.getExpiry())) &&
    
    
    ((!repPeriodIsSet() && !rhs.repPeriodIsSet()) || (repPeriodIsSet() && rhs.repPeriodIsSet() && getRepPeriod() == rhs.getRepPeriod())) &&
    
    
    ((!sampRatioIsSet() && !rhs.sampRatioIsSet()) || (sampRatioIsSet() && rhs.sampRatioIsSet() && getSampRatio() == rhs.getSampRatio())) &&
    
    
    ((!partitioningCriteriaIsSet() && !rhs.partitioningCriteriaIsSet()) || (partitioningCriteriaIsSet() && rhs.partitioningCriteriaIsSet() && getPartitioningCriteria() == rhs.getPartitioningCriteria())) &&
    
    
    ((!notifFlagIsSet() && !rhs.notifFlagIsSet()) || (notifFlagIsSet() && rhs.notifFlagIsSet() && getNotifFlag() == rhs.getNotifFlag()))
    
    ;
}

bool UpfEventMode::operator!=(const UpfEventMode& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const UpfEventMode& o)
{
    j = nlohmann::json();
    j["trigger"] = o.m_Trigger;
    if(o.maxReportsIsSet())
        j["maxReports"] = o.m_MaxReports;
    if(o.expiryIsSet())
        j["expiry"] = o.m_Expiry;
    if(o.repPeriodIsSet())
        j["repPeriod"] = o.m_RepPeriod;
    if(o.sampRatioIsSet())
        j["sampRatio"] = o.m_SampRatio;
    if(o.partitioningCriteriaIsSet() || !o.m_PartitioningCriteria.empty())
        j["partitioningCriteria"] = o.m_PartitioningCriteria;
    if(o.notifFlagIsSet())
        j["notifFlag"] = o.m_NotifFlag;
    
}

void from_json(const nlohmann::json& j, UpfEventMode& o)
{
    j.at("trigger").get_to(o.m_Trigger);
    if(j.find("maxReports") != j.end())
    {
        j.at("maxReports").get_to(o.m_MaxReports);
        o.m_MaxReportsIsSet = true;
    } 
    if(j.find("expiry") != j.end())
    {
        j.at("expiry").get_to(o.m_Expiry);
        o.m_ExpiryIsSet = true;
    } 
    if(j.find("repPeriod") != j.end())
    {
        j.at("repPeriod").get_to(o.m_RepPeriod);
        o.m_RepPeriodIsSet = true;
    } 
    if(j.find("sampRatio") != j.end())
    {
        j.at("sampRatio").get_to(o.m_SampRatio);
        o.m_SampRatioIsSet = true;
    } 
    if(j.find("partitioningCriteria") != j.end())
    {
        j.at("partitioningCriteria").get_to(o.m_PartitioningCriteria);
        o.m_PartitioningCriteriaIsSet = true;
    } 
    if(j.find("notifFlag") != j.end())
    {
        j.at("notifFlag").get_to(o.m_NotifFlag);
        o.m_NotifFlagIsSet = true;
    } 
    
}

org::openapitools::server::model::UpfEventTrigger UpfEventMode::getTrigger() const
{
    return m_Trigger;
}
void UpfEventMode::setTrigger(org::openapitools::server::model::UpfEventTrigger const& value)
{
    m_Trigger = value;
}
int32_t UpfEventMode::getMaxReports() const
{
    return m_MaxReports;
}
void UpfEventMode::setMaxReports(int32_t const value)
{
    m_MaxReports = value;
    m_MaxReportsIsSet = true;
}
bool UpfEventMode::maxReportsIsSet() const
{
    return m_MaxReportsIsSet;
}
void UpfEventMode::unsetMaxReports()
{
    m_MaxReportsIsSet = false;
}
std::string UpfEventMode::getExpiry() const
{
    return m_Expiry;
}
void UpfEventMode::setExpiry(std::string const& value)
{
    m_Expiry = value;
    m_ExpiryIsSet = true;
}
bool UpfEventMode::expiryIsSet() const
{
    return m_ExpiryIsSet;
}
void UpfEventMode::unsetExpiry()
{
    m_ExpiryIsSet = false;
}
int32_t UpfEventMode::getRepPeriod() const
{
    return m_RepPeriod;
}
void UpfEventMode::setRepPeriod(int32_t const value)
{
    m_RepPeriod = value;
    m_RepPeriodIsSet = true;
}
bool UpfEventMode::repPeriodIsSet() const
{
    return m_RepPeriodIsSet;
}
void UpfEventMode::unsetRepPeriod()
{
    m_RepPeriodIsSet = false;
}
int32_t UpfEventMode::getSampRatio() const
{
    return m_SampRatio;
}
void UpfEventMode::setSampRatio(int32_t const value)
{
    m_SampRatio = value;
    m_SampRatioIsSet = true;
}
bool UpfEventMode::sampRatioIsSet() const
{
    return m_SampRatioIsSet;
}
void UpfEventMode::unsetSampRatio()
{
    m_SampRatioIsSet = false;
}
std::vector<org::openapitools::server::model::PartitioningCriteria> UpfEventMode::getPartitioningCriteria() const
{
    return m_PartitioningCriteria;
}
void UpfEventMode::setPartitioningCriteria(std::vector<org::openapitools::server::model::PartitioningCriteria> const& value)
{
    m_PartitioningCriteria = value;
    m_PartitioningCriteriaIsSet = true;
}
bool UpfEventMode::partitioningCriteriaIsSet() const
{
    return m_PartitioningCriteriaIsSet;
}
void UpfEventMode::unsetPartitioningCriteria()
{
    m_PartitioningCriteriaIsSet = false;
}
org::openapitools::server::model::NotificationFlag UpfEventMode::getNotifFlag() const
{
    return m_NotifFlag;
}
void UpfEventMode::setNotifFlag(org::openapitools::server::model::NotificationFlag const& value)
{
    m_NotifFlag = value;
    m_NotifFlagIsSet = true;
}
bool UpfEventMode::notifFlagIsSet() const
{
    return m_NotifFlagIsSet;
}
void UpfEventMode::unsetNotifFlag()
{
    m_NotifFlagIsSet = false;
}


} // namespace org::openapitools::server::model

