/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UpfEventMode.h
 *
 * UPF Event Mode
 */

#ifndef UpfEventMode_H_
#define UpfEventMode_H_


#include "UpfEventTrigger.h"
#include "NotificationFlag.h"
#include "PartitioningCriteria.h"
#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// UPF Event Mode
/// </summary>
class  UpfEventMode
{
public:
    UpfEventMode();
    virtual ~UpfEventMode() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const UpfEventMode& rhs) const;
    bool operator!=(const UpfEventMode& rhs) const;

    /////////////////////////////////////////////
    /// UpfEventMode members

    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::UpfEventTrigger getTrigger() const;
    void setTrigger(org::openapitools::server::model::UpfEventTrigger const& value);
    /// <summary>
    /// 
    /// </summary>
    int32_t getMaxReports() const;
    void setMaxReports(int32_t const value);
    bool maxReportsIsSet() const;
    void unsetMaxReports();
    /// <summary>
    /// string with format &#39;date-time&#39; as defined in OpenAPI.
    /// </summary>
    std::string getExpiry() const;
    void setExpiry(std::string const& value);
    bool expiryIsSet() const;
    void unsetExpiry();
    /// <summary>
    /// indicating a time in seconds.
    /// </summary>
    int32_t getRepPeriod() const;
    void setRepPeriod(int32_t const value);
    bool repPeriodIsSet() const;
    void unsetRepPeriod();
    /// <summary>
    /// Unsigned integer indicating Sampling Ratio (see clauses 4.15.1 of 3GPP TS 23.502), expressed in percent.  
    /// </summary>
    int32_t getSampRatio() const;
    void setSampRatio(int32_t const value);
    bool sampRatioIsSet() const;
    void unsetSampRatio();
    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::PartitioningCriteria> getPartitioningCriteria() const;
    void setPartitioningCriteria(std::vector<org::openapitools::server::model::PartitioningCriteria> const& value);
    bool partitioningCriteriaIsSet() const;
    void unsetPartitioningCriteria();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::NotificationFlag getNotifFlag() const;
    void setNotifFlag(org::openapitools::server::model::NotificationFlag const& value);
    bool notifFlagIsSet() const;
    void unsetNotifFlag();

    friend  void to_json(nlohmann::json& j, const UpfEventMode& o);
    friend  void from_json(const nlohmann::json& j, UpfEventMode& o);
protected:
    org::openapitools::server::model::UpfEventTrigger m_Trigger;

    int32_t m_MaxReports;
    bool m_MaxReportsIsSet;
    std::string m_Expiry;
    bool m_ExpiryIsSet;
    int32_t m_RepPeriod;
    bool m_RepPeriodIsSet;
    int32_t m_SampRatio;
    bool m_SampRatioIsSet;
    std::vector<org::openapitools::server::model::PartitioningCriteria> m_PartitioningCriteria;
    bool m_PartitioningCriteriaIsSet;
    org::openapitools::server::model::NotificationFlag m_NotifFlag;
    bool m_NotifFlagIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* UpfEventMode_H_ */
