/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "UpfEvent.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

UpfEvent::UpfEvent()
{
    m_ImmediateFlag = false;
    m_ImmediateFlagIsSet = false;
    m_MeasurementTypesIsSet = false;
    m_AppIdsIsSet = false;
    m_TrafficFiltersIsSet = false;
    m_GranularityOfMeasurementIsSet = false;
    m_ReportingSuggestionInfoIsSet = false;
    
}

void UpfEvent::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool UpfEvent::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool UpfEvent::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "UpfEvent" : pathPrefix;

                 
    if (measurementTypesIsSet())
    {
        const std::vector<org::openapitools::server::model::MeasurementType>& value = m_MeasurementTypes;
        const std::string currentValuePath = _pathPrefix + ".measurementTypes";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const org::openapitools::server::model::MeasurementType& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".measurementTypes") && success;
 
                i++;
            }
        }

    }
         
    if (appIdsIsSet())
    {
        const std::vector<org::openapitools::server::model::std::string>& value = m_AppIds;
        const std::string currentValuePath = _pathPrefix + ".appIds";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const std::string& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        
 
                i++;
            }
        }

    }
         
    if (trafficFiltersIsSet())
    {
        const std::vector<org::openapitools::server::model::FlowInfo>& value = m_TrafficFilters;
        const std::string currentValuePath = _pathPrefix + ".trafficFilters";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const org::openapitools::server::model::FlowInfo& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".trafficFilters") && success;
 
                i++;
            }
        }

    }
            
    return success;
}

bool UpfEvent::operator==(const UpfEvent& rhs) const
{
    return
    
    
    (getType() == rhs.getType())
     &&
    
    
    ((!immediateFlagIsSet() && !rhs.immediateFlagIsSet()) || (immediateFlagIsSet() && rhs.immediateFlagIsSet() && isImmediateFlag() == rhs.isImmediateFlag())) &&
    
    
    ((!measurementTypesIsSet() && !rhs.measurementTypesIsSet()) || (measurementTypesIsSet() && rhs.measurementTypesIsSet() && getMeasurementTypes() == rhs.getMeasurementTypes())) &&
    
    
    ((!appIdsIsSet() && !rhs.appIdsIsSet()) || (appIdsIsSet() && rhs.appIdsIsSet() && getAppIds() == rhs.getAppIds())) &&
    
    
    ((!trafficFiltersIsSet() && !rhs.trafficFiltersIsSet()) || (trafficFiltersIsSet() && rhs.trafficFiltersIsSet() && getTrafficFilters() == rhs.getTrafficFilters())) &&
    
    
    ((!granularityOfMeasurementIsSet() && !rhs.granularityOfMeasurementIsSet()) || (granularityOfMeasurementIsSet() && rhs.granularityOfMeasurementIsSet() && getGranularityOfMeasurement() == rhs.getGranularityOfMeasurement())) &&
    
    
    ((!reportingSuggestionInfoIsSet() && !rhs.reportingSuggestionInfoIsSet()) || (reportingSuggestionInfoIsSet() && rhs.reportingSuggestionInfoIsSet() && getReportingSuggestionInfo() == rhs.getReportingSuggestionInfo()))
    
    ;
}

bool UpfEvent::operator!=(const UpfEvent& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const UpfEvent& o)
{
    j = nlohmann::json();
    j["type"] = o.m_Type;
    if(o.immediateFlagIsSet())
        j["immediateFlag"] = o.m_ImmediateFlag;
    if(o.measurementTypesIsSet() || !o.m_MeasurementTypes.empty())
        j["measurementTypes"] = o.m_MeasurementTypes;
    if(o.appIdsIsSet() || !o.m_AppIds.empty())
        j["appIds"] = o.m_AppIds;
    if(o.trafficFiltersIsSet() || !o.m_TrafficFilters.empty())
        j["trafficFilters"] = o.m_TrafficFilters;
    if(o.granularityOfMeasurementIsSet())
        j["granularityOfMeasurement"] = o.m_GranularityOfMeasurement;
    if(o.reportingSuggestionInfoIsSet())
        j["reportingSuggestionInfo"] = o.m_ReportingSuggestionInfo;
    
}

void from_json(const nlohmann::json& j, UpfEvent& o)
{
    j.at("type").get_to(o.m_Type);
    if(j.find("immediateFlag") != j.end())
    {
        j.at("immediateFlag").get_to(o.m_ImmediateFlag);
        o.m_ImmediateFlagIsSet = true;
    } 
    if(j.find("measurementTypes") != j.end())
    {
        j.at("measurementTypes").get_to(o.m_MeasurementTypes);
        o.m_MeasurementTypesIsSet = true;
    } 
    if(j.find("appIds") != j.end())
    {
        j.at("appIds").get_to(o.m_AppIds);
        o.m_AppIdsIsSet = true;
    } 
    if(j.find("trafficFilters") != j.end())
    {
        j.at("trafficFilters").get_to(o.m_TrafficFilters);
        o.m_TrafficFiltersIsSet = true;
    } 
    if(j.find("granularityOfMeasurement") != j.end())
    {
        j.at("granularityOfMeasurement").get_to(o.m_GranularityOfMeasurement);
        o.m_GranularityOfMeasurementIsSet = true;
    } 
    if(j.find("reportingSuggestionInfo") != j.end())
    {
        j.at("reportingSuggestionInfo").get_to(o.m_ReportingSuggestionInfo);
        o.m_ReportingSuggestionInfoIsSet = true;
    } 
    
}

org::openapitools::server::model::EventType UpfEvent::getType() const
{
    return m_Type;
}
void UpfEvent::setType(org::openapitools::server::model::EventType const& value)
{
    m_Type = value;
}
bool UpfEvent::isImmediateFlag() const
{
    return m_ImmediateFlag;
}
void UpfEvent::setImmediateFlag(bool const value)
{
    m_ImmediateFlag = value;
    m_ImmediateFlagIsSet = true;
}
bool UpfEvent::immediateFlagIsSet() const
{
    return m_ImmediateFlagIsSet;
}
void UpfEvent::unsetImmediateFlag()
{
    m_ImmediateFlagIsSet = false;
}
std::vector<org::openapitools::server::model::MeasurementType> UpfEvent::getMeasurementTypes() const
{
    return m_MeasurementTypes;
}
void UpfEvent::setMeasurementTypes(std::vector<org::openapitools::server::model::MeasurementType> const& value)
{
    m_MeasurementTypes = value;
    m_MeasurementTypesIsSet = true;
}
bool UpfEvent::measurementTypesIsSet() const
{
    return m_MeasurementTypesIsSet;
}
void UpfEvent::unsetMeasurementTypes()
{
    m_MeasurementTypesIsSet = false;
}
std::vector<org::openapitools::server::model::std::string> UpfEvent::getAppIds() const
{
    return m_AppIds;
}
void UpfEvent::setAppIds(std::vector<org::openapitools::server::model::std::string> const& value)
{
    m_AppIds = value;
    m_AppIdsIsSet = true;
}
bool UpfEvent::appIdsIsSet() const
{
    return m_AppIdsIsSet;
}
void UpfEvent::unsetAppIds()
{
    m_AppIdsIsSet = false;
}
std::vector<org::openapitools::server::model::FlowInfo> UpfEvent::getTrafficFilters() const
{
    return m_TrafficFilters;
}
void UpfEvent::setTrafficFilters(std::vector<org::openapitools::server::model::FlowInfo> const& value)
{
    m_TrafficFilters = value;
    m_TrafficFiltersIsSet = true;
}
bool UpfEvent::trafficFiltersIsSet() const
{
    return m_TrafficFiltersIsSet;
}
void UpfEvent::unsetTrafficFilters()
{
    m_TrafficFiltersIsSet = false;
}
org::openapitools::server::model::GranularityOfMeasurement UpfEvent::getGranularityOfMeasurement() const
{
    return m_GranularityOfMeasurement;
}
void UpfEvent::setGranularityOfMeasurement(org::openapitools::server::model::GranularityOfMeasurement const& value)
{
    m_GranularityOfMeasurement = value;
    m_GranularityOfMeasurementIsSet = true;
}
bool UpfEvent::granularityOfMeasurementIsSet() const
{
    return m_GranularityOfMeasurementIsSet;
}
void UpfEvent::unsetGranularityOfMeasurement()
{
    m_GranularityOfMeasurementIsSet = false;
}
org::openapitools::server::model::ReportingSuggestionInformation UpfEvent::getReportingSuggestionInfo() const
{
    return m_ReportingSuggestionInfo;
}
void UpfEvent::setReportingSuggestionInfo(org::openapitools::server::model::ReportingSuggestionInformation const& value)
{
    m_ReportingSuggestionInfo = value;
    m_ReportingSuggestionInfoIsSet = true;
}
bool UpfEvent::reportingSuggestionInfoIsSet() const
{
    return m_ReportingSuggestionInfoIsSet;
}
void UpfEvent::unsetReportingSuggestionInfo()
{
    m_ReportingSuggestionInfoIsSet = false;
}


} // namespace org::openapitools::server::model

