/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "UpfEventSubscription.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

UpfEventSubscription::UpfEventSubscription()
{
    m_EventNotifyUri = "";
    m_NotifyCorrelationId = "";
    m_NfId = "";
    m_UeIpAddressIsSet = false;
    m_Supi = "";
    m_SupiIsSet = false;
    m_Gpsi = "";
    m_GpsiIsSet = false;
    m_Pei = "";
    m_PeiIsSet = false;
    m_AnyUe = false;
    m_AnyUeIsSet = false;
    m_Dnn = "";
    m_DnnIsSet = false;
    m_SnssaiIsSet = false;
    
}

void UpfEventSubscription::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool UpfEventSubscription::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool UpfEventSubscription::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "UpfEventSubscription" : pathPrefix;

         
    
    /* EventList */ {
        const std::vector<org::openapitools::server::model::UpfEvent>& value = m_EventList;
        const std::string currentValuePath = _pathPrefix + ".eventList";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const org::openapitools::server::model::UpfEvent& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".eventList") && success;
 
                i++;
            }
        }

    }
                             
    if (supiIsSet())
    {
        const std::string& value = m_Supi;
        const std::string currentValuePath = _pathPrefix + ".supi";
                
        

    }
         
    if (gpsiIsSet())
    {
        const std::string& value = m_Gpsi;
        const std::string currentValuePath = _pathPrefix + ".gpsi";
                
        

    }
         
    if (peiIsSet())
    {
        const std::string& value = m_Pei;
        const std::string currentValuePath = _pathPrefix + ".pei";
                
        

    }
                
    return success;
}

bool UpfEventSubscription::operator==(const UpfEventSubscription& rhs) const
{
    return
    
    
    (getEventList() == rhs.getEventList())
     &&
    
    (getEventNotifyUri() == rhs.getEventNotifyUri())
     &&
    
    (getNotifyCorrelationId() == rhs.getNotifyCorrelationId())
     &&
    
    (getEventReportingMode() == rhs.getEventReportingMode())
     &&
    
    (getNfId() == rhs.getNfId())
     &&
    
    
    ((!ueIpAddressIsSet() && !rhs.ueIpAddressIsSet()) || (ueIpAddressIsSet() && rhs.ueIpAddressIsSet() && getUeIpAddress() == rhs.getUeIpAddress())) &&
    
    
    ((!supiIsSet() && !rhs.supiIsSet()) || (supiIsSet() && rhs.supiIsSet() && getSupi() == rhs.getSupi())) &&
    
    
    ((!gpsiIsSet() && !rhs.gpsiIsSet()) || (gpsiIsSet() && rhs.gpsiIsSet() && getGpsi() == rhs.getGpsi())) &&
    
    
    ((!peiIsSet() && !rhs.peiIsSet()) || (peiIsSet() && rhs.peiIsSet() && getPei() == rhs.getPei())) &&
    
    
    ((!anyUeIsSet() && !rhs.anyUeIsSet()) || (anyUeIsSet() && rhs.anyUeIsSet() && isAnyUe() == rhs.isAnyUe())) &&
    
    
    ((!dnnIsSet() && !rhs.dnnIsSet()) || (dnnIsSet() && rhs.dnnIsSet() && getDnn() == rhs.getDnn())) &&
    
    
    ((!snssaiIsSet() && !rhs.snssaiIsSet()) || (snssaiIsSet() && rhs.snssaiIsSet() && getSnssai() == rhs.getSnssai()))
    
    ;
}

bool UpfEventSubscription::operator!=(const UpfEventSubscription& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const UpfEventSubscription& o)
{
    j = nlohmann::json();
    j["eventList"] = o.m_EventList;
    j["eventNotifyUri"] = o.m_EventNotifyUri;
    j["notifyCorrelationId"] = o.m_NotifyCorrelationId;
    j["eventReportingMode"] = o.m_EventReportingMode;
    j["nfId"] = o.m_NfId;
    if(o.ueIpAddressIsSet())
        j["ueIpAddress"] = o.m_UeIpAddress;
    if(o.supiIsSet())
        j["supi"] = o.m_Supi;
    if(o.gpsiIsSet())
        j["gpsi"] = o.m_Gpsi;
    if(o.peiIsSet())
        j["pei"] = o.m_Pei;
    if(o.anyUeIsSet())
        j["anyUe"] = o.m_AnyUe;
    if(o.dnnIsSet())
        j["dnn"] = o.m_Dnn;
    if(o.snssaiIsSet())
        j["snssai"] = o.m_Snssai;
    
}

void from_json(const nlohmann::json& j, UpfEventSubscription& o)
{
    j.at("eventList").get_to(o.m_EventList);
    j.at("eventNotifyUri").get_to(o.m_EventNotifyUri);
    j.at("notifyCorrelationId").get_to(o.m_NotifyCorrelationId);
    j.at("eventReportingMode").get_to(o.m_EventReportingMode);
    j.at("nfId").get_to(o.m_NfId);
    if(j.find("ueIpAddress") != j.end())
    {
        j.at("ueIpAddress").get_to(o.m_UeIpAddress);
        o.m_UeIpAddressIsSet = true;
    } 
    if(j.find("supi") != j.end())
    {
        j.at("supi").get_to(o.m_Supi);
        o.m_SupiIsSet = true;
    } 
    if(j.find("gpsi") != j.end())
    {
        j.at("gpsi").get_to(o.m_Gpsi);
        o.m_GpsiIsSet = true;
    } 
    if(j.find("pei") != j.end())
    {
        j.at("pei").get_to(o.m_Pei);
        o.m_PeiIsSet = true;
    } 
    if(j.find("anyUe") != j.end())
    {
        j.at("anyUe").get_to(o.m_AnyUe);
        o.m_AnyUeIsSet = true;
    } 
    if(j.find("dnn") != j.end())
    {
        j.at("dnn").get_to(o.m_Dnn);
        o.m_DnnIsSet = true;
    } 
    if(j.find("snssai") != j.end())
    {
        j.at("snssai").get_to(o.m_Snssai);
        o.m_SnssaiIsSet = true;
    } 
    
}

std::vector<org::openapitools::server::model::UpfEvent> UpfEventSubscription::getEventList() const
{
    return m_EventList;
}
void UpfEventSubscription::setEventList(std::vector<org::openapitools::server::model::UpfEvent> const& value)
{
    m_EventList = value;
}
std::string UpfEventSubscription::getEventNotifyUri() const
{
    return m_EventNotifyUri;
}
void UpfEventSubscription::setEventNotifyUri(std::string const& value)
{
    m_EventNotifyUri = value;
}
std::string UpfEventSubscription::getNotifyCorrelationId() const
{
    return m_NotifyCorrelationId;
}
void UpfEventSubscription::setNotifyCorrelationId(std::string const& value)
{
    m_NotifyCorrelationId = value;
}
org::openapitools::server::model::UpfEventMode UpfEventSubscription::getEventReportingMode() const
{
    return m_EventReportingMode;
}
void UpfEventSubscription::setEventReportingMode(org::openapitools::server::model::UpfEventMode const& value)
{
    m_EventReportingMode = value;
}
std::string UpfEventSubscription::getNfId() const
{
    return m_NfId;
}
void UpfEventSubscription::setNfId(std::string const& value)
{
    m_NfId = value;
}
org::openapitools::server::model::IpAddr UpfEventSubscription::getUeIpAddress() const
{
    return m_UeIpAddress;
}
void UpfEventSubscription::setUeIpAddress(org::openapitools::server::model::IpAddr const& value)
{
    m_UeIpAddress = value;
    m_UeIpAddressIsSet = true;
}
bool UpfEventSubscription::ueIpAddressIsSet() const
{
    return m_UeIpAddressIsSet;
}
void UpfEventSubscription::unsetUeIpAddress()
{
    m_UeIpAddressIsSet = false;
}
std::string UpfEventSubscription::getSupi() const
{
    return m_Supi;
}
void UpfEventSubscription::setSupi(std::string const& value)
{
    m_Supi = value;
    m_SupiIsSet = true;
}
bool UpfEventSubscription::supiIsSet() const
{
    return m_SupiIsSet;
}
void UpfEventSubscription::unsetSupi()
{
    m_SupiIsSet = false;
}
std::string UpfEventSubscription::getGpsi() const
{
    return m_Gpsi;
}
void UpfEventSubscription::setGpsi(std::string const& value)
{
    m_Gpsi = value;
    m_GpsiIsSet = true;
}
bool UpfEventSubscription::gpsiIsSet() const
{
    return m_GpsiIsSet;
}
void UpfEventSubscription::unsetGpsi()
{
    m_GpsiIsSet = false;
}
std::string UpfEventSubscription::getPei() const
{
    return m_Pei;
}
void UpfEventSubscription::setPei(std::string const& value)
{
    m_Pei = value;
    m_PeiIsSet = true;
}
bool UpfEventSubscription::peiIsSet() const
{
    return m_PeiIsSet;
}
void UpfEventSubscription::unsetPei()
{
    m_PeiIsSet = false;
}
bool UpfEventSubscription::isAnyUe() const
{
    return m_AnyUe;
}
void UpfEventSubscription::setAnyUe(bool const value)
{
    m_AnyUe = value;
    m_AnyUeIsSet = true;
}
bool UpfEventSubscription::anyUeIsSet() const
{
    return m_AnyUeIsSet;
}
void UpfEventSubscription::unsetAnyUe()
{
    m_AnyUeIsSet = false;
}
std::string UpfEventSubscription::getDnn() const
{
    return m_Dnn;
}
void UpfEventSubscription::setDnn(std::string const& value)
{
    m_Dnn = value;
    m_DnnIsSet = true;
}
bool UpfEventSubscription::dnnIsSet() const
{
    return m_DnnIsSet;
}
void UpfEventSubscription::unsetDnn()
{
    m_DnnIsSet = false;
}
org::openapitools::server::model::Snssai UpfEventSubscription::getSnssai() const
{
    return m_Snssai;
}
void UpfEventSubscription::setSnssai(org::openapitools::server::model::Snssai const& value)
{
    m_Snssai = value;
    m_SnssaiIsSet = true;
}
bool UpfEventSubscription::snssaiIsSet() const
{
    return m_SnssaiIsSet;
}
void UpfEventSubscription::unsetSnssai()
{
    m_SnssaiIsSet = false;
}


} // namespace org::openapitools::server::model

