/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UpfEventSubscription.h
 *
 * UPF Event Subscription
 */

#ifndef UpfEventSubscription_H_
#define UpfEventSubscription_H_


#include "IpAddr.h"
#include "UpfEvent.h"
#include <string>
#include "Snssai.h"
#include <vector>
#include "UpfEventMode.h"
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// UPF Event Subscription
/// </summary>
class  UpfEventSubscription
{
public:
    UpfEventSubscription();
    virtual ~UpfEventSubscription() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const UpfEventSubscription& rhs) const;
    bool operator!=(const UpfEventSubscription& rhs) const;

    /////////////////////////////////////////////
    /// UpfEventSubscription members

    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::UpfEvent> getEventList() const;
    void setEventList(std::vector<org::openapitools::server::model::UpfEvent> const& value);
    /// <summary>
    /// String providing an URI formatted according to RFC 3986.
    /// </summary>
    std::string getEventNotifyUri() const;
    void setEventNotifyUri(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::string getNotifyCorrelationId() const;
    void setNotifyCorrelationId(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::UpfEventMode getEventReportingMode() const;
    void setEventReportingMode(org::openapitools::server::model::UpfEventMode const& value);
    /// <summary>
    /// String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.  
    /// </summary>
    std::string getNfId() const;
    void setNfId(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::IpAddr getUeIpAddress() const;
    void setUeIpAddress(org::openapitools::server::model::IpAddr const& value);
    bool ueIpAddressIsSet() const;
    void unsetUeIpAddress();
    /// <summary>
    /// String identifying a Supi that shall contain either an IMSI, a network specific identifier, a Global Cable Identifier (GCI) or a Global Line Identifier (GLI) as specified in clause  2.2A of 3GPP TS 23.003. It shall be formatted as follows  - for an IMSI \&quot;imsi-&lt;imsi&gt;\&quot;, where &lt;imsi&gt; shall be formatted according to clause 2.2    of 3GPP TS 23.003 that describes an IMSI.  - for a network specific identifier \&quot;nai-&lt;nai&gt;, where &lt;nai&gt; shall be formatted    according to clause 28.7.2 of 3GPP TS 23.003 that describes an NAI.  - for a GCI \&quot;gci-&lt;gci&gt;\&quot;, where &lt;gci&gt; shall be formatted according to clause 28.15.2    of 3GPP TS 23.003.  - for a GLI \&quot;gli-&lt;gli&gt;\&quot;, where &lt;gli&gt; shall be formatted according to clause 28.16.2 of    3GPP TS 23.003.To enable that the value is used as part of an URI, the string shall    only contain characters allowed according to the \&quot;lower-with-hyphen\&quot; naming convention    defined in 3GPP TS 29.501. 
    /// </summary>
    std::string getSupi() const;
    void setSupi(std::string const& value);
    bool supiIsSet() const;
    void unsetSupi();
    /// <summary>
    /// String identifying a Gpsi shall contain either an External Id or an MSISDN.  It shall be formatted as follows -External Identifier&#x3D; \&quot;extid-&#39;extid&#39;, where &#39;extid&#39;  shall be formatted according to clause 19.7.2 of 3GPP TS 23.003 that describes an  External Identifier.  
    /// </summary>
    std::string getGpsi() const;
    void setGpsi(std::string const& value);
    bool gpsiIsSet() const;
    void unsetGpsi();
    /// <summary>
    /// String representing a Permanent Equipment Identifier that may contain - an IMEI or IMEISV, as  specified in clause 6.2 of 3GPP TS 23.003; a MAC address for a 5G-RG or FN-RG via  wireline  access, with an indication that this address cannot be trusted for regulatory purpose if this  address cannot be used as an Equipment Identifier of the FN-RG, as specified in clause 4.7.7  of 3GPP TS23.316. Examples are imei-012345678901234 or imeisv-0123456789012345.  
    /// </summary>
    std::string getPei() const;
    void setPei(std::string const& value);
    bool peiIsSet() const;
    void unsetPei();
    /// <summary>
    /// 
    /// </summary>
    bool isAnyUe() const;
    void setAnyUe(bool const value);
    bool anyUeIsSet() const;
    void unsetAnyUe();
    /// <summary>
    /// String representing a Data Network as defined in clause 9A of 3GPP TS 23.003;  it shall contain either a DNN Network Identifier, or a full DNN with both the Network  Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots  (e.g. \&quot;Label1.Label2.Label3\&quot;). 
    /// </summary>
    std::string getDnn() const;
    void setDnn(std::string const& value);
    bool dnnIsSet() const;
    void unsetDnn();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::Snssai getSnssai() const;
    void setSnssai(org::openapitools::server::model::Snssai const& value);
    bool snssaiIsSet() const;
    void unsetSnssai();

    friend  void to_json(nlohmann::json& j, const UpfEventSubscription& o);
    friend  void from_json(const nlohmann::json& j, UpfEventSubscription& o);
protected:
    std::vector<org::openapitools::server::model::UpfEvent> m_EventList;

    std::string m_EventNotifyUri;

    std::string m_NotifyCorrelationId;

    org::openapitools::server::model::UpfEventMode m_EventReportingMode;

    std::string m_NfId;

    org::openapitools::server::model::IpAddr m_UeIpAddress;
    bool m_UeIpAddressIsSet;
    std::string m_Supi;
    bool m_SupiIsSet;
    std::string m_Gpsi;
    bool m_GpsiIsSet;
    std::string m_Pei;
    bool m_PeiIsSet;
    bool m_AnyUe;
    bool m_AnyUeIsSet;
    std::string m_Dnn;
    bool m_DnnIsSet;
    org::openapitools::server::model::Snssai m_Snssai;
    bool m_SnssaiIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* UpfEventSubscription_H_ */
