/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UpfEvent.h
 *
 * UPF Event
 */

#ifndef UpfEvent_H_
#define UpfEvent_H_


#include "MeasurementType.h"
#include "ReportingSuggestionInformation.h"
#include "FlowInfo.h"
#include "GranularityOfMeasurement.h"
#include <string>
#include "EventType.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// UPF Event
/// </summary>
class  UpfEvent
{
public:
    UpfEvent();
    virtual ~UpfEvent() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const UpfEvent& rhs) const;
    bool operator!=(const UpfEvent& rhs) const;

    /////////////////////////////////////////////
    /// UpfEvent members

    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::EventType getType() const;
    void setType(org::openapitools::server::model::EventType const& value);
    /// <summary>
    /// 
    /// </summary>
    bool isImmediateFlag() const;
    void setImmediateFlag(bool const value);
    bool immediateFlagIsSet() const;
    void unsetImmediateFlag();
    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::MeasurementType> getMeasurementTypes() const;
    void setMeasurementTypes(std::vector<org::openapitools::server::model::MeasurementType> const& value);
    bool measurementTypesIsSet() const;
    void unsetMeasurementTypes();
    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::std::string> getAppIds() const;
    void setAppIds(std::vector<org::openapitools::server::model::std::string> const& value);
    bool appIdsIsSet() const;
    void unsetAppIds();
    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::FlowInfo> getTrafficFilters() const;
    void setTrafficFilters(std::vector<org::openapitools::server::model::FlowInfo> const& value);
    bool trafficFiltersIsSet() const;
    void unsetTrafficFilters();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::GranularityOfMeasurement getGranularityOfMeasurement() const;
    void setGranularityOfMeasurement(org::openapitools::server::model::GranularityOfMeasurement const& value);
    bool granularityOfMeasurementIsSet() const;
    void unsetGranularityOfMeasurement();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::ReportingSuggestionInformation getReportingSuggestionInfo() const;
    void setReportingSuggestionInfo(org::openapitools::server::model::ReportingSuggestionInformation const& value);
    bool reportingSuggestionInfoIsSet() const;
    void unsetReportingSuggestionInfo();

    friend  void to_json(nlohmann::json& j, const UpfEvent& o);
    friend  void from_json(const nlohmann::json& j, UpfEvent& o);
protected:
    org::openapitools::server::model::EventType m_Type;

    bool m_ImmediateFlag;
    bool m_ImmediateFlagIsSet;
    std::vector<org::openapitools::server::model::MeasurementType> m_MeasurementTypes;
    bool m_MeasurementTypesIsSet;
    std::vector<org::openapitools::server::model::std::string> m_AppIds;
    bool m_AppIdsIsSet;
    std::vector<org::openapitools::server::model::FlowInfo> m_TrafficFilters;
    bool m_TrafficFiltersIsSet;
    org::openapitools::server::model::GranularityOfMeasurement m_GranularityOfMeasurement;
    bool m_GranularityOfMeasurementIsSet;
    org::openapitools::server::model::ReportingSuggestionInformation m_ReportingSuggestionInfo;
    bool m_ReportingSuggestionInfoIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* UpfEvent_H_ */
