/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "UserDataUsageMeasurements.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

UserDataUsageMeasurements::UserDataUsageMeasurements()
{
    m_AppId = "";
    m_AppIdIsSet = false;
    m_FlowInfoIsSet = false;
    m_VolumeMeasurementIsSet = false;
    m_ThroughputMeasurementIsSet = false;
    m_ApplicationRelatedInformationIsSet = false;
    m_ThroughputStatisticsMeasurementIsSet = false;
    
}

void UserDataUsageMeasurements::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool UserDataUsageMeasurements::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool UserDataUsageMeasurements::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "UserDataUsageMeasurements" : pathPrefix;

                            
    return success;
}

bool UserDataUsageMeasurements::operator==(const UserDataUsageMeasurements& rhs) const
{
    return
    
    
    
    ((!appIdIsSet() && !rhs.appIdIsSet()) || (appIdIsSet() && rhs.appIdIsSet() && getAppId() == rhs.getAppId())) &&
    
    
    ((!flowInfoIsSet() && !rhs.flowInfoIsSet()) || (flowInfoIsSet() && rhs.flowInfoIsSet() && getFlowInfo() == rhs.getFlowInfo())) &&
    
    
    ((!volumeMeasurementIsSet() && !rhs.volumeMeasurementIsSet()) || (volumeMeasurementIsSet() && rhs.volumeMeasurementIsSet() && getVolumeMeasurement() == rhs.getVolumeMeasurement())) &&
    
    
    ((!throughputMeasurementIsSet() && !rhs.throughputMeasurementIsSet()) || (throughputMeasurementIsSet() && rhs.throughputMeasurementIsSet() && getThroughputMeasurement() == rhs.getThroughputMeasurement())) &&
    
    
    ((!applicationRelatedInformationIsSet() && !rhs.applicationRelatedInformationIsSet()) || (applicationRelatedInformationIsSet() && rhs.applicationRelatedInformationIsSet() && getApplicationRelatedInformation() == rhs.getApplicationRelatedInformation())) &&
    
    
    ((!throughputStatisticsMeasurementIsSet() && !rhs.throughputStatisticsMeasurementIsSet()) || (throughputStatisticsMeasurementIsSet() && rhs.throughputStatisticsMeasurementIsSet() && getThroughputStatisticsMeasurement() == rhs.getThroughputStatisticsMeasurement()))
    
    ;
}

bool UserDataUsageMeasurements::operator!=(const UserDataUsageMeasurements& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const UserDataUsageMeasurements& o)
{
    j = nlohmann::json();
    if(o.appIdIsSet())
        j["appId"] = o.m_AppId;
    if(o.flowInfoIsSet())
        j["flowInfo"] = o.m_FlowInfo;
    if(o.volumeMeasurementIsSet())
        j["volumeMeasurement"] = o.m_VolumeMeasurement;
    if(o.throughputMeasurementIsSet())
        j["throughputMeasurement"] = o.m_ThroughputMeasurement;
    if(o.applicationRelatedInformationIsSet())
        j["applicationRelatedInformation"] = o.m_ApplicationRelatedInformation;
    if(o.throughputStatisticsMeasurementIsSet())
        j["throughputStatisticsMeasurement"] = o.m_ThroughputStatisticsMeasurement;
    
}

void from_json(const nlohmann::json& j, UserDataUsageMeasurements& o)
{
    if(j.find("appId") != j.end())
    {
        j.at("appId").get_to(o.m_AppId);
        o.m_AppIdIsSet = true;
    } 
    if(j.find("flowInfo") != j.end())
    {
        j.at("flowInfo").get_to(o.m_FlowInfo);
        o.m_FlowInfoIsSet = true;
    } 
    if(j.find("volumeMeasurement") != j.end())
    {
        j.at("volumeMeasurement").get_to(o.m_VolumeMeasurement);
        o.m_VolumeMeasurementIsSet = true;
    } 
    if(j.find("throughputMeasurement") != j.end())
    {
        j.at("throughputMeasurement").get_to(o.m_ThroughputMeasurement);
        o.m_ThroughputMeasurementIsSet = true;
    } 
    if(j.find("applicationRelatedInformation") != j.end())
    {
        j.at("applicationRelatedInformation").get_to(o.m_ApplicationRelatedInformation);
        o.m_ApplicationRelatedInformationIsSet = true;
    } 
    if(j.find("throughputStatisticsMeasurement") != j.end())
    {
        j.at("throughputStatisticsMeasurement").get_to(o.m_ThroughputStatisticsMeasurement);
        o.m_ThroughputStatisticsMeasurementIsSet = true;
    } 
    
}

std::string UserDataUsageMeasurements::getAppId() const
{
    return m_AppId;
}
void UserDataUsageMeasurements::setAppId(std::string const& value)
{
    m_AppId = value;
    m_AppIdIsSet = true;
}
bool UserDataUsageMeasurements::appIdIsSet() const
{
    return m_AppIdIsSet;
}
void UserDataUsageMeasurements::unsetAppId()
{
    m_AppIdIsSet = false;
}
org::openapitools::server::model::FlowInfo UserDataUsageMeasurements::getFlowInfo() const
{
    return m_FlowInfo;
}
void UserDataUsageMeasurements::setFlowInfo(org::openapitools::server::model::FlowInfo const& value)
{
    m_FlowInfo = value;
    m_FlowInfoIsSet = true;
}
bool UserDataUsageMeasurements::flowInfoIsSet() const
{
    return m_FlowInfoIsSet;
}
void UserDataUsageMeasurements::unsetFlowInfo()
{
    m_FlowInfoIsSet = false;
}
org::openapitools::server::model::VolumeMeasurement UserDataUsageMeasurements::getVolumeMeasurement() const
{
    return m_VolumeMeasurement;
}
void UserDataUsageMeasurements::setVolumeMeasurement(org::openapitools::server::model::VolumeMeasurement const& value)
{
    m_VolumeMeasurement = value;
    m_VolumeMeasurementIsSet = true;
}
bool UserDataUsageMeasurements::volumeMeasurementIsSet() const
{
    return m_VolumeMeasurementIsSet;
}
void UserDataUsageMeasurements::unsetVolumeMeasurement()
{
    m_VolumeMeasurementIsSet = false;
}
org::openapitools::server::model::ThroughputMeasurement UserDataUsageMeasurements::getThroughputMeasurement() const
{
    return m_ThroughputMeasurement;
}
void UserDataUsageMeasurements::setThroughputMeasurement(org::openapitools::server::model::ThroughputMeasurement const& value)
{
    m_ThroughputMeasurement = value;
    m_ThroughputMeasurementIsSet = true;
}
bool UserDataUsageMeasurements::throughputMeasurementIsSet() const
{
    return m_ThroughputMeasurementIsSet;
}
void UserDataUsageMeasurements::unsetThroughputMeasurement()
{
    m_ThroughputMeasurementIsSet = false;
}
org::openapitools::server::model::ApplicationRelatedInformation UserDataUsageMeasurements::getApplicationRelatedInformation() const
{
    return m_ApplicationRelatedInformation;
}
void UserDataUsageMeasurements::setApplicationRelatedInformation(org::openapitools::server::model::ApplicationRelatedInformation const& value)
{
    m_ApplicationRelatedInformation = value;
    m_ApplicationRelatedInformationIsSet = true;
}
bool UserDataUsageMeasurements::applicationRelatedInformationIsSet() const
{
    return m_ApplicationRelatedInformationIsSet;
}
void UserDataUsageMeasurements::unsetApplicationRelatedInformation()
{
    m_ApplicationRelatedInformationIsSet = false;
}
org::openapitools::server::model::ThroughputStatisticsMeasurement UserDataUsageMeasurements::getThroughputStatisticsMeasurement() const
{
    return m_ThroughputStatisticsMeasurement;
}
void UserDataUsageMeasurements::setThroughputStatisticsMeasurement(org::openapitools::server::model::ThroughputStatisticsMeasurement const& value)
{
    m_ThroughputStatisticsMeasurement = value;
    m_ThroughputStatisticsMeasurementIsSet = true;
}
bool UserDataUsageMeasurements::throughputStatisticsMeasurementIsSet() const
{
    return m_ThroughputStatisticsMeasurementIsSet;
}
void UserDataUsageMeasurements::unsetThroughputStatisticsMeasurement()
{
    m_ThroughputStatisticsMeasurementIsSet = false;
}


} // namespace org::openapitools::server::model

