/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UserDataUsageMeasurements.h
 *
 * User Data Usage Measurements either for the PDU session, or the app-id, or the data flow 
 */

#ifndef UserDataUsageMeasurements_H_
#define UserDataUsageMeasurements_H_


#include "ThroughputStatisticsMeasurement.h"
#include "FlowInfo.h"
#include "ApplicationRelatedInformation.h"
#include "ThroughputMeasurement.h"
#include <string>
#include "VolumeMeasurement.h"
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// User Data Usage Measurements either for the PDU session, or the app-id, or the data flow 
/// </summary>
class  UserDataUsageMeasurements
{
public:
    UserDataUsageMeasurements();
    virtual ~UserDataUsageMeasurements() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const UserDataUsageMeasurements& rhs) const;
    bool operator!=(const UserDataUsageMeasurements& rhs) const;

    /////////////////////////////////////////////
    /// UserDataUsageMeasurements members

    /// <summary>
    /// String providing an application identifier.
    /// </summary>
    std::string getAppId() const;
    void setAppId(std::string const& value);
    bool appIdIsSet() const;
    void unsetAppId();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::FlowInfo getFlowInfo() const;
    void setFlowInfo(org::openapitools::server::model::FlowInfo const& value);
    bool flowInfoIsSet() const;
    void unsetFlowInfo();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::VolumeMeasurement getVolumeMeasurement() const;
    void setVolumeMeasurement(org::openapitools::server::model::VolumeMeasurement const& value);
    bool volumeMeasurementIsSet() const;
    void unsetVolumeMeasurement();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::ThroughputMeasurement getThroughputMeasurement() const;
    void setThroughputMeasurement(org::openapitools::server::model::ThroughputMeasurement const& value);
    bool throughputMeasurementIsSet() const;
    void unsetThroughputMeasurement();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::ApplicationRelatedInformation getApplicationRelatedInformation() const;
    void setApplicationRelatedInformation(org::openapitools::server::model::ApplicationRelatedInformation const& value);
    bool applicationRelatedInformationIsSet() const;
    void unsetApplicationRelatedInformation();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::ThroughputStatisticsMeasurement getThroughputStatisticsMeasurement() const;
    void setThroughputStatisticsMeasurement(org::openapitools::server::model::ThroughputStatisticsMeasurement const& value);
    bool throughputStatisticsMeasurementIsSet() const;
    void unsetThroughputStatisticsMeasurement();

    friend  void to_json(nlohmann::json& j, const UserDataUsageMeasurements& o);
    friend  void from_json(const nlohmann::json& j, UserDataUsageMeasurements& o);
protected:
    std::string m_AppId;
    bool m_AppIdIsSet;
    org::openapitools::server::model::FlowInfo m_FlowInfo;
    bool m_FlowInfoIsSet;
    org::openapitools::server::model::VolumeMeasurement m_VolumeMeasurement;
    bool m_VolumeMeasurementIsSet;
    org::openapitools::server::model::ThroughputMeasurement m_ThroughputMeasurement;
    bool m_ThroughputMeasurementIsSet;
    org::openapitools::server::model::ApplicationRelatedInformation m_ApplicationRelatedInformation;
    bool m_ApplicationRelatedInformationIsSet;
    org::openapitools::server::model::ThroughputStatisticsMeasurement m_ThroughputStatisticsMeasurement;
    bool m_ThroughputStatisticsMeasurementIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* UserDataUsageMeasurements_H_ */
