/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * VolumeMeasurement.h
 *
 * Volume Measurement information
 */

#ifndef VolumeMeasurement_H_
#define VolumeMeasurement_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Volume Measurement information
/// </summary>
class  VolumeMeasurement
{
public:
    VolumeMeasurement();
    virtual ~VolumeMeasurement() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const VolumeMeasurement& rhs) const;
    bool operator!=(const VolumeMeasurement& rhs) const;

    /////////////////////////////////////////////
    /// VolumeMeasurement members

    /// <summary>
    /// String representing a Traffic Volume measured in bytes; the prefixes follow the symbols from The International System of Units, and represent x1000 multipliers. 
    /// </summary>
    std::string getTotalVolume() const;
    void setTotalVolume(std::string const& value);
    bool totalVolumeIsSet() const;
    void unsetTotalVolume();
    /// <summary>
    /// String representing a Traffic Volume measured in bytes; the prefixes follow the symbols from The International System of Units, and represent x1000 multipliers. 
    /// </summary>
    std::string getUlVolume() const;
    void setUlVolume(std::string const& value);
    bool ulVolumeIsSet() const;
    void unsetUlVolume();
    /// <summary>
    /// String representing a Traffic Volume measured in bytes; the prefixes follow the symbols from The International System of Units, and represent x1000 multipliers. 
    /// </summary>
    std::string getDlVolume() const;
    void setDlVolume(std::string const& value);
    bool dlVolumeIsSet() const;
    void unsetDlVolume();
    /// <summary>
    /// Integer where the allowed values correspond to the value range of an unsigned 64-bit integer. 
    /// </summary>
    int32_t getTotalNbOfPackets() const;
    void setTotalNbOfPackets(int32_t const value);
    bool totalNbOfPacketsIsSet() const;
    void unsetTotalNbOfPackets();
    /// <summary>
    /// Integer where the allowed values correspond to the value range of an unsigned 64-bit integer. 
    /// </summary>
    int32_t getUlNbOfPackets() const;
    void setUlNbOfPackets(int32_t const value);
    bool ulNbOfPacketsIsSet() const;
    void unsetUlNbOfPackets();
    /// <summary>
    /// Integer where the allowed values correspond to the value range of an unsigned 64-bit integer. 
    /// </summary>
    int32_t getDlNbOfPackets() const;
    void setDlNbOfPackets(int32_t const value);
    bool dlNbOfPacketsIsSet() const;
    void unsetDlNbOfPackets();

    friend  void to_json(nlohmann::json& j, const VolumeMeasurement& o);
    friend  void from_json(const nlohmann::json& j, VolumeMeasurement& o);
protected:
    std::string m_TotalVolume;
    bool m_TotalVolumeIsSet;
    std::string m_UlVolume;
    bool m_UlVolumeIsSet;
    std::string m_DlVolume;
    bool m_DlVolumeIsSet;
    int32_t m_TotalNbOfPackets;
    bool m_TotalNbOfPacketsIsSet;
    int32_t m_UlNbOfPackets;
    bool m_UlNbOfPacketsIsSet;
    int32_t m_DlNbOfPackets;
    bool m_DlNbOfPacketsIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* VolumeMeasurement_H_ */
