/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "VolumeMeasurement.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

VolumeMeasurement::VolumeMeasurement()
{
    m_TotalVolume = "";
    m_TotalVolumeIsSet = false;
    m_UlVolume = "";
    m_UlVolumeIsSet = false;
    m_DlVolume = "";
    m_DlVolumeIsSet = false;
    m_TotalNbOfPackets = 0;
    m_TotalNbOfPacketsIsSet = false;
    m_UlNbOfPackets = 0;
    m_UlNbOfPacketsIsSet = false;
    m_DlNbOfPackets = 0;
    m_DlNbOfPacketsIsSet = false;
    
}

void VolumeMeasurement::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool VolumeMeasurement::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool VolumeMeasurement::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "VolumeMeasurement" : pathPrefix;

         
    if (totalVolumeIsSet())
    {
        const std::string& value = m_TotalVolume;
        const std::string currentValuePath = _pathPrefix + ".totalVolume";
                
        

    }
         
    if (ulVolumeIsSet())
    {
        const std::string& value = m_UlVolume;
        const std::string currentValuePath = _pathPrefix + ".ulVolume";
                
        

    }
         
    if (dlVolumeIsSet())
    {
        const std::string& value = m_DlVolume;
        const std::string currentValuePath = _pathPrefix + ".dlVolume";
                
        

    }
         
    if (totalNbOfPacketsIsSet())
    {
        const int32_t& value = m_TotalNbOfPackets;
        const std::string currentValuePath = _pathPrefix + ".totalNbOfPackets";
                
        
        if (value < 0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0;";
        }
        if (value > -1)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to -1;";
        }

    }
         
    if (ulNbOfPacketsIsSet())
    {
        const int32_t& value = m_UlNbOfPackets;
        const std::string currentValuePath = _pathPrefix + ".ulNbOfPackets";
                
        
        if (value < 0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0;";
        }
        if (value > -1)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to -1;";
        }

    }
         
    if (dlNbOfPacketsIsSet())
    {
        const int32_t& value = m_DlNbOfPackets;
        const std::string currentValuePath = _pathPrefix + ".dlNbOfPackets";
                
        
        if (value < 0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0;";
        }
        if (value > -1)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to -1;";
        }

    }
    
    return success;
}

bool VolumeMeasurement::operator==(const VolumeMeasurement& rhs) const
{
    return
    
    
    
    ((!totalVolumeIsSet() && !rhs.totalVolumeIsSet()) || (totalVolumeIsSet() && rhs.totalVolumeIsSet() && getTotalVolume() == rhs.getTotalVolume())) &&
    
    
    ((!ulVolumeIsSet() && !rhs.ulVolumeIsSet()) || (ulVolumeIsSet() && rhs.ulVolumeIsSet() && getUlVolume() == rhs.getUlVolume())) &&
    
    
    ((!dlVolumeIsSet() && !rhs.dlVolumeIsSet()) || (dlVolumeIsSet() && rhs.dlVolumeIsSet() && getDlVolume() == rhs.getDlVolume())) &&
    
    
    ((!totalNbOfPacketsIsSet() && !rhs.totalNbOfPacketsIsSet()) || (totalNbOfPacketsIsSet() && rhs.totalNbOfPacketsIsSet() && getTotalNbOfPackets() == rhs.getTotalNbOfPackets())) &&
    
    
    ((!ulNbOfPacketsIsSet() && !rhs.ulNbOfPacketsIsSet()) || (ulNbOfPacketsIsSet() && rhs.ulNbOfPacketsIsSet() && getUlNbOfPackets() == rhs.getUlNbOfPackets())) &&
    
    
    ((!dlNbOfPacketsIsSet() && !rhs.dlNbOfPacketsIsSet()) || (dlNbOfPacketsIsSet() && rhs.dlNbOfPacketsIsSet() && getDlNbOfPackets() == rhs.getDlNbOfPackets()))
    
    ;
}

bool VolumeMeasurement::operator!=(const VolumeMeasurement& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const VolumeMeasurement& o)
{
    j = nlohmann::json();
    if(o.totalVolumeIsSet())
        j["totalVolume"] = o.m_TotalVolume;
    if(o.ulVolumeIsSet())
        j["ulVolume"] = o.m_UlVolume;
    if(o.dlVolumeIsSet())
        j["dlVolume"] = o.m_DlVolume;
    if(o.totalNbOfPacketsIsSet())
        j["totalNbOfPackets"] = o.m_TotalNbOfPackets;
    if(o.ulNbOfPacketsIsSet())
        j["ulNbOfPackets"] = o.m_UlNbOfPackets;
    if(o.dlNbOfPacketsIsSet())
        j["dlNbOfPackets"] = o.m_DlNbOfPackets;
    
}

void from_json(const nlohmann::json& j, VolumeMeasurement& o)
{
    if(j.find("totalVolume") != j.end())
    {
        j.at("totalVolume").get_to(o.m_TotalVolume);
        o.m_TotalVolumeIsSet = true;
    } 
    if(j.find("ulVolume") != j.end())
    {
        j.at("ulVolume").get_to(o.m_UlVolume);
        o.m_UlVolumeIsSet = true;
    } 
    if(j.find("dlVolume") != j.end())
    {
        j.at("dlVolume").get_to(o.m_DlVolume);
        o.m_DlVolumeIsSet = true;
    } 
    if(j.find("totalNbOfPackets") != j.end())
    {
        j.at("totalNbOfPackets").get_to(o.m_TotalNbOfPackets);
        o.m_TotalNbOfPacketsIsSet = true;
    } 
    if(j.find("ulNbOfPackets") != j.end())
    {
        j.at("ulNbOfPackets").get_to(o.m_UlNbOfPackets);
        o.m_UlNbOfPacketsIsSet = true;
    } 
    if(j.find("dlNbOfPackets") != j.end())
    {
        j.at("dlNbOfPackets").get_to(o.m_DlNbOfPackets);
        o.m_DlNbOfPacketsIsSet = true;
    } 
    
}

std::string VolumeMeasurement::getTotalVolume() const
{
    return m_TotalVolume;
}
void VolumeMeasurement::setTotalVolume(std::string const& value)
{
    m_TotalVolume = value;
    m_TotalVolumeIsSet = true;
}
bool VolumeMeasurement::totalVolumeIsSet() const
{
    return m_TotalVolumeIsSet;
}
void VolumeMeasurement::unsetTotalVolume()
{
    m_TotalVolumeIsSet = false;
}
std::string VolumeMeasurement::getUlVolume() const
{
    return m_UlVolume;
}
void VolumeMeasurement::setUlVolume(std::string const& value)
{
    m_UlVolume = value;
    m_UlVolumeIsSet = true;
}
bool VolumeMeasurement::ulVolumeIsSet() const
{
    return m_UlVolumeIsSet;
}
void VolumeMeasurement::unsetUlVolume()
{
    m_UlVolumeIsSet = false;
}
std::string VolumeMeasurement::getDlVolume() const
{
    return m_DlVolume;
}
void VolumeMeasurement::setDlVolume(std::string const& value)
{
    m_DlVolume = value;
    m_DlVolumeIsSet = true;
}
bool VolumeMeasurement::dlVolumeIsSet() const
{
    return m_DlVolumeIsSet;
}
void VolumeMeasurement::unsetDlVolume()
{
    m_DlVolumeIsSet = false;
}
int32_t VolumeMeasurement::getTotalNbOfPackets() const
{
    return m_TotalNbOfPackets;
}
void VolumeMeasurement::setTotalNbOfPackets(int32_t const value)
{
    m_TotalNbOfPackets = value;
    m_TotalNbOfPacketsIsSet = true;
}
bool VolumeMeasurement::totalNbOfPacketsIsSet() const
{
    return m_TotalNbOfPacketsIsSet;
}
void VolumeMeasurement::unsetTotalNbOfPackets()
{
    m_TotalNbOfPacketsIsSet = false;
}
int32_t VolumeMeasurement::getUlNbOfPackets() const
{
    return m_UlNbOfPackets;
}
void VolumeMeasurement::setUlNbOfPackets(int32_t const value)
{
    m_UlNbOfPackets = value;
    m_UlNbOfPacketsIsSet = true;
}
bool VolumeMeasurement::ulNbOfPacketsIsSet() const
{
    return m_UlNbOfPacketsIsSet;
}
void VolumeMeasurement::unsetUlNbOfPackets()
{
    m_UlNbOfPacketsIsSet = false;
}
int32_t VolumeMeasurement::getDlNbOfPackets() const
{
    return m_DlNbOfPackets;
}
void VolumeMeasurement::setDlNbOfPackets(int32_t const value)
{
    m_DlNbOfPackets = value;
    m_DlNbOfPacketsIsSet = true;
}
bool VolumeMeasurement::dlNbOfPacketsIsSet() const
{
    return m_DlNbOfPacketsIsSet;
}
void VolumeMeasurement::unsetDlNbOfPackets()
{
    m_DlNbOfPacketsIsSet = false;
}


} // namespace org::openapitools::server::model

