# Configuration File
### This file can be used by all NFs
### Some fields are specific to an NF and will be ignored by other NFs

## NOTE ON YAML ANCHORS ##
# We use YAML anchors to ease the configuration and to avoid duplicating parts of the configuration.
# This is especially true for the SNSSAIs, as we have to define them for multiple NFs.
# Please note that the use of anchors is not mandatory, and you can define the SNSSAI in each NF yourself.
# You can read more about anchors here: https://yaml.org/spec/1.2.2/#anchors-and-aliases

############# Common configuration

# Log level for all the NFs
log_level:
  general: debug

# If you enable registration, the other NFs will use the NRF discovery mechanism
register_nf:
  general: yes

http_version: 1

############## SBI Interfaces
### Each NF takes its local SBI interfaces and remote interfaces from here, unless it gets them using NRF discovery mechanisms
nfs:
  amf:
    host: openxg-amf
    sbi:
      port: 8001
      api_version: v1
      interface_name: eth0
    n2:
      interface_name: eth0
      port: 38412
  smf:
    host: openxg-smf
    sbi:
      port: 8002
      api_version: v1
      interface_name: eth0
    n4:
      interface_name: eth0
      port: 8805
  upf:
    host: openxg-upf
    sbi:
      port: 8003
      api_version: v1
      interface_name: enp6s0
    n3:
      interface_name: enp1s0f0np0
      port: 2152
    n4:
      interface_name: enp6s0
      port: 8805
    n6:
      interface_name: enp1s0f1np1
    n9:
      interface_name: enp1s0f1np1
      port: 2152
  udm:
    host: openxg-udm
    sbi:
      port: 8004
      api_version: v1
      interface_name: eth0
  udr:
    host: openxg-udr
    sbi:
      port: 8005
      api_version: v1
      interface_name: eth0
  ausf:
    host: openxg-ausf
    sbi:
      port: 8006
      api_version: v1
      interface_name: eth0
  nrf:
    host: openxg-nrf
    sbi:
      port: 8007
      api_version: v1
      interface_name: eth0

#### Common for UDR and AMF
database:
  host: 172.11.200.10
  user: root
  type: mysql
  password: 123456
  database_name: OpenXG-DB
  generate_random: true
  connection_timeout: 300 # seconds

## general single_nssai configuration
## Defines YAML anchors, which are reused in the config file
snssais:
  - &embb_slice1
    sst: 1
  - &embb_slice2
    sst: 1
    sd: 000001 # in hex

############## NF-specific configuration
nrf:
  nrf_name: "OpenXG-NRF"
udr:
  udr_name: "OpenXG-UDR"
udm:
  udm_name: "OpenXG-UDM"
ausf:
  ausf_name: "OpenXG-AUSF"
amf:
  amf_name: "OpenXG-AMF"
  # This really depends on if we want to keep the "mini" version or not
  support_features_options:
    enable_simple_scenario: no # "no" by default with the normal deployment scenarios with AMF/SMF/UPF/AUSF/UDM/UDR/NRF.
                               # set it to "yes" to use with the minimalist deployment scenario (including only AMF/SMF/UPF) by using the internal AUSF/UDM implemented inside AMF.
                               # There's no NRF in this scenario, SMF info is taken from "nfs" section.
    enable_nssf: no
    enable_smf_selection: yes
  relative_capacity: 30
  statistics_timer_interval: 20  # in seconds
  emergency_support: false
  served_guami_list:
    - mcc: 466
      mnc: 92
      amf_region_id: 01
      amf_set_id: 001
      amf_pointer: 01
    - mcc: 001
      mnc: 01
      amf_region_id: 01
      amf_set_id: 001
      amf_pointer: 01
  plmn_support_list:
    - mcc: 466
      mnc: 92
      tac: 0x0064
      nssai:
        - *embb_slice1
        - *embb_slice2
  supported_integrity_algorithms:
    - "NIA2"
    - "NIA1"
    - "NIA0"
  supported_encryption_algorithms:
    - "NEA0"
    - "NEA1"
    - "NEA2"

smf:
  smf_name: "OpenXG-SMF"
  ue_mtu: 1500
  support_features:
    use_local_subscription_info: yes # Use infos from local_subscription_info or from UDM
    use_local_pcc_rules: yes # Use infos from local_pcc_rules or from PCF
  # we resolve from NRF, this is just to configure usage_reporting
  upfs:
    - host: openxg-upf
      config:
        enable_usage_reporting: no
  ue_dns:
    primary_ipv4: "114.114.114.114"
    primary_ipv6: "2001:4860:4860::8888"
    secondary_ipv4: "8.8.8.8"
    secondary_ipv6: "2001:4860:4860::8888"
  ims:
    pcscf_ipv4: "127.0.0.1"
    pcscf_ipv6: "fe80::7915:f408:1787:db8b"
  # the DNN you configure here should be configured in "dnns"
  # follows the SmfInfo datatype from 3GPP TS 29.510
  smf_info:
    sNssaiSmfInfoList:
      - sNssai: *embb_slice1
        dnnSmfInfoList:
          - dnn: "ctnet"
      - sNssai: *embb_slice1
        dnnSmfInfoList:
          - dnn: "internet"
      - sNssai: *embb_slice1
        dnnSmfInfoList:
          - dnn: "default"
  local_subscription_infos:
    - single_nssai: *embb_slice1
      dnn: "ctnet"
      qos_profile:
        5qi: 9
        session_ambr_ul: "100Gbps"
        session_ambr_dl: "100Gbps"
    - single_nssai: *embb_slice1
      dnn: "internet"
      qos_profile:
        5qi: 9
        session_ambr_ul: "100Gbps"
        session_ambr_dl: "100Gbps"
    - single_nssai: *embb_slice1
      dnn: "default"
      qos_profile:
        5qi: 9
        session_ambr_ul: "100Gbps"
        session_ambr_dl: "100Gbps"

upf:
  upf_name: "OpenXG-UPF"
  support_features:
    enable_bpf_datapath: yes  # If "yes": BPF is used as datapath else simpleswitch is used, DEFAULT= no
    enable_qos: no            # Only supported for BPF datapath. If "yes" we use qdisc to manage the QoS
    enable_snat: no           # If "no": Source natting is done for UE, DEFAULT= no
  remote_n6_gw: oai-ext-dn
  smfs:
    - host: oai-smf            # To be used for PFCP association in case of no-NRF
  upf_info:
    sNssaiUpfInfoList:
      - sNssai: *embb_slice1
        dnnUpfInfoList:
          - dnn: "ctnet"
      - sNssai: *embb_slice1
        dnnUpfInfoList:
          - dnn: "internet"
      - sNssai: *embb_slice1
        dnnUpfInfoList:
          - dnn: "default"

## DNN configuration
dnns:
  - dnn: "ctnet"
    pdu_session_type: "IPV4V6"
    ipv4_subnet: "12.1.1.0/24"
  - dnn: "internet"
    pdu_session_type: "IPV4"
    ipv4_subnet: "12.1.1.0/24"
  - dnn: "default"
    pdu_session_type: "IPV4"
    ipv4_subnet: "12.1.1.0/26"
  - dnn: "ims"
    pdu_session_type: "IPV4V6"
    ipv4_subnet: "14.1.1.2/24"
