/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
#ifndef __FAR_TC_USER_H__
#define __FAR_TC_USER_H__

#include <ProgramLifeCycle.hpp>
#include <atomic>
#include <linux/bpf.h>  // manage maps (e.g. bpf_update*)
#include <memory>
#include <mutex>
#include <signal.h>  // signals
#include <far_tc_kernel_skel.h>
#include <wrappers/BPFMap.hpp>
#include <BPFProgram.h>
#include "interfaces.h"

#include <qos_flow.h>
#include <pfcp_session.hpp>
class BPFMaps;
class BPFMap;
class SessionManager;
// class RulesUtilities;

using FARTCProgramLifeCycle = ProgramLifeCycle<far_tc_kernel_c>;

/**
 * @brief Singleton class to abstract the UPF bpf tc program.
 */
class FARTCProgram : public BPFProgram {
 public:
  /*---------------------------------------------------------------------------------------------------------------*/
  /**
   * @brief Construct a new FARTCProgram object.
   *
   */
  explicit FARTCProgram();

  /*---------------------------------------------------------------------------------------------------------------*/
  /**
   * @brief Destroy the FARTCProgram object
   */
  virtual ~FARTCProgram();

  /*---------------------------------------------------------------------------------------------------------------*/
  /**
   * @brief Setup the tc BPF program when QoS Feature is disabled
   *
   */
  void setup();

  /*---------------------------------------------------------------------------------------------------------------*/
  /**
   * @brief Get the BPFMaps object.
   *
   * @return std::shared_ptr<BPFMaps> The reference of the BPFMaps.
   */
  std::shared_ptr<BPFMaps> getMaps();

  /*---------------------------------------------------------------------------------------------------------------*/
  /**
   * @brief Tear downs the BPF program.
   *
   */
  void tearDown();

  /*---------------------------------------------------------------------------------------------------------------*/
  /**
   * @brief Get the MacPduSession Map object for ETH PDU sessions.
   *
   * @return std::shared_ptr<BPFMap> The pdi to index map.
   */
  std::shared_ptr<BPFMap> getETHSessionMappingMap() const;

  /*---------------------------------------------------------------------------------------------------------------*/
  /**
   * @brief Get the Egress Interface Map object.
   *
   * @return std::shared_ptr<BPFMap> The egress interface map.
   */
  std::shared_ptr<BPFMap> getEgressInterfaceMap() const;

  /*---------------------------------------------------------------------------------------------------------------*/
 private:
  /**
   * @brief Initialize BPF wrappers maps.
   *
   */
  void initializeMaps();

  /*---------------------------------------------------------------------------------------------------------------*/
  // The reference of the bpf maps.
  std::shared_ptr<BPFMaps> mpMaps;

  /*---------------------------------------------------------------------------------------------------------------*/
  // The skeleton of the UPF program generated by bpftool.
  // ProgramLifeCycle is the owner of the pointer.
  far_tc_kernel_c* spSkeleton;

  /*---------------------------------------------------------------------------------------------------------------*/

  // The BPF lifecycle program.
  std::shared_ptr<FARTCProgramLifeCycle> mpLifeCycle;

  /*---------------------------------------------------------------------------------------------------------------*/
  // The egress interface map.
  std::shared_ptr<BPFMap> mpEgressInterfaceMap;

  /*---------------------------------------------------------------------------------------------------------------*/
  std::shared_ptr<BPFMap> mpETHSessionMappingMap;
};

#endif  // __FAR_TC_USER_H__
