#ifndef __PFCP_SESSION_PDR_LOOKUP_EBPF_XDP_PRGRM_USER_H__
#define __PFCP_SESSION_PDR_LOOKUP_EBPF_XDP_PRGRM_USER_H__

#include <ProgramLifeCycle.hpp>
#include <atomic>
#include <linux/bpf.h> // manage maps (e.g. bpf_update*)
#include <memory>
#include <mutex>
#include <signal.h> // signals
#include <pfcp_session_pdr_lookup_ebpf_xdp_prgrm_kernel_skel.h>
#include <wrappers/BPFMap.hpp>

#include "interfaces.h"

class BPFMaps;
class BPFMap;
class SessionManager;
class RulesUtilities;


using PFCP_Session_PDR_LookupLifeCycle = ProgramLifeCycle<pfcp_session_pdr_lookup_ebpf_xdp_prgrm_kernel_c>;

/**
 * @brief Singleton class to abrastract the UPF bpf program.
 */
class PFCP_Session_PDR_Lookup
{
public:
  /**
   * @brief Construct a new PFCP_Session_PDR_Lookup object.
   *
   */
  explicit PFCP_Session_PDR_Lookup(const std::string& gtpInterface, const std::string& udpInterface);
  
  /*****************************************************************************************************************/
  /**
   * @brief Destroy the PFCP_Session_PDR_Lookup object
   */
  virtual ~PFCP_Session_PDR_Lookup();

  /*****************************************************************************************************************/
  /**
   * @brief Setup the BPF program.
   *
   */
  void setup();

  /*****************************************************************************************************************/
  /**
   * @brief Get the BPFMaps object.
   *
   * @return std::shared_ptr<BPFMaps> The reference of the BPFMaps.
   */
  std::shared_ptr<BPFMaps> getMaps();
  
  /*****************************************************************************************************************/
  /**
   * @brief Tear downs the BPF program.
   *
   */
  void tearDown();

  /*****************************************************************************************************************/
  /**
   * @brief Update program int map.
   *
   * @param key The key which will be inserted the program file descriptor.
   * @param fd The file descriptor.
   */
  void updateProgramMap(uint32_t key, uint32_t fd);
  
  /*****************************************************************************************************************/
  /**
   * @brief Remove program in map.
   *
   * @param key The key which will be remove in the program map.
   */
  void removeProgramMap(uint32_t key);

  /*****************************************************************************************************************/
  /**
   * @brief Get the TEID to session Map object.
   *
   * @return std::shared_ptr<BPFMap> The TEID to fd map.
   */
  std::shared_ptr<BPFMap> getTeidSessionMap() const;

  /*****************************************************************************************************************/
  /**
   * @brief Get the UE IP to session Map object.
   *
   * @return std::shared_ptr<BPFMap> The UE IP to fd map.
   */
  std::shared_ptr<BPFMap> getUeIpSessionMap() const;

  /*****************************************************************************************************************/
  /**
   * @brief Get the NextProgRule Map object.
   *
   * @return std::shared_ptr<BPFMap> The NextProgRule to fd map.
   */
  std::shared_ptr<BPFMap> getNextProgRuleMap() const;

  /*****************************************************************************************************************/
  /**
   * @brief Get the NextProgRuleIndex Map object.
   *
   * @return std::shared_ptr<BPFMap> The pdi to index map.
   */
  std::shared_ptr<BPFMap> getNextProgRuleIndexMap() const;

  /*****************************************************************************************************************/
  /**
   * @brief Get the iface Map object.
   *
   * @return std::shared_ptr<BPFMap> The iface_name.
   */
  std::shared_ptr<BPFMap> getIfaceMap() const;




private:
  /**
   * @brief Initialize BPF wrappers maps.
   *
   */
  void initializeMaps();

  // The reference of the bpf maps.
  std::shared_ptr<BPFMaps> mpMaps;

  // The skeleton of the UPF program generated by bpftool.
  // ProgramLifeCycle is the owner of the pointer.
  pfcp_session_pdr_lookup_ebpf_xdp_prgrm_kernel_c *spSkeleton;

  // The program eBPF map.
  std::shared_ptr<BPFMap> mpTeidSessionMap;

  // The program eBPF map.
  std::shared_ptr<BPFMap> mpUeIpSessionMap;

  // The pdi key to program index map.
  std::shared_ptr<BPFMap> mpNextProgRuleIndexMap;

  // The next prog rule map.
  std::shared_ptr<BPFMap> mpNextProgRuleMap;

  // The BPF lifecycle program.
  std::shared_ptr<PFCP_Session_PDR_LookupLifeCycle> mpLifeCycle;

  // The GTP interface.
  std::string mGTPInterface;

  // The UDP interface.
  std::string mUDPInterface;

   // The iface map.
  std::shared_ptr<BPFMap> mpIfaceMap;


  struct interface gtp_interface, udp_interface;
  


};

#endif // __PFCP_SESSION_PDR_LOOKUP_EBPF_XDP_PRGRM_USER_H__
