#ifndef __QER_EBPF_TC_PRGRM_USER_H__
#define __QER_EBPF_TC_PRGRM_USER_H__

#include <ProgramLifeCycle.hpp>
#include <atomic>
#include <linux/bpf.h>  // manage maps (e.g. bpf_update*)
#include <memory>
#include <mutex>
#include <signal.h>  // signals
#include <qer_ebpf_tc_prgrm_kernel_skel.h>
#include <wrappers/BPFMap.hpp>
#include <BPFProgram.h>
#include "interfaces.h"

#include "interfaces.h"

class BPFMaps;
class BPFMap;
class SessionManager;
class RulesUtilities;

using QERProgramLifeCycle = ProgramLifeCycle<qer_ebpf_tc_prgrm_kernel_c>;

/**
 * @brief Singleton class to abstract the UPF bpf tc program.
 */
class QERProgram : public BPFProgram {
 public:
  /**
   * @brief Construct a new QERProgram object.
   *
   */
  explicit QERProgram();

  /*****************************************************************************************************************/
  /**
   * @brief Destroy the QERProgram object
   */
  virtual ~QERProgram();

  /*****************************************************************************************************************/

  /**
   * @brief Setup the BPF program.
   *
   */
  void setup();

  /*****************************************************************************************************************/
  /**
   * @brief Get the BPFMaps object.
   *
   * @return std::shared_ptr<BPFMaps> The reference of the BPFMaps.
   */
  std::shared_ptr<BPFMaps> getMaps();

  /*****************************************************************************************************************/
  /**
   * @brief Tear downs the BPF program.
   *
   */
  void tearDown();
  /*****************************************************************************************************************/

  /**
   * @brief Update program int map.
   *
   * @param key The key which will be inserted the program file descriptor.
   * @param fd The file descriptor.
   */
  void updateProgramMap(uint32_t key, uint32_t fd);

  /*****************************************************************************************************************/
  /**
   * @brief Remove program in map.
   *
   * @param key The key which will be remove in the program map.
   */
  void removeProgramMap(uint32_t key);

  /*****************************************************************************************************************/
  /**
   * @brief Get the TEID to session Map object.
   *
   * @return std::shared_ptr<BPFMap> The TEID to fd map.
   */
  std::shared_ptr<BPFMap> getQERMap() const;

  /*****************************************************************************************************************/
  /**
   * @brief Get the Egress Interface Map object.
   *
   * @return std::shared_ptr<BPFMap> The egress interface map.
   */
  std::shared_ptr<BPFMap> getEgressInterfaceMap() const;

  /*****************************************************************************************************************/
  /**
   * @brief Get the n3 GTP-U Tunnel Map object.
   *
   * @return std::shared_ptr<BPFMap>  The seid value of the PDU session associated
   * with the n3 GTP-U Tunnel.
   */
  std::shared_ptr<BPFMap> geGtpUTunnelMap() const;

  /*****************************************************************************************************************/
  /**
   * @brief Get the Filter Map object.
   *
   * @return std::shared_ptr<BPFMap> The filter.
   */
  std::shared_ptr<BPFMap> getFilterMap() const;

  /*****************************************************************************************************************/
 private:
  /**
   * @brief Initialize BPF wrappers maps.
   *
   */
  void initializeMaps();

  /*****************************************************************************************************************/
  // The reference of the bpf maps.
  std::shared_ptr<BPFMaps> mpMaps;

  /*****************************************************************************************************************/
  // The skeleton of the UPF program generated by bpftool.
  // ProgramLifeCycle is the owner of the pointer.
  qer_ebpf_tc_prgrm_kernel_c* spSkeleton;

  /*****************************************************************************************************************/
  // The GTP-U Tunnel map.
  std::shared_ptr<BPFMap> mpGtpUTunnelMap;

  /*****************************************************************************************************************/
  // The Filter map.
  std::shared_ptr<BPFMap> mpFilterMap;

  /*****************************************************************************************************************/
};

#endif  // __QER_EBPF_TC_PRGRM_USER_H__
