/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

#ifndef FILE_RFC_1877_SEEN
#define FILE_RFC_1877_SEEN

#define IPCP_OPTION_PRIMARY_DNS_SERVER_IP_ADDRESS (0x81)
#define IPCP_OPTION_PRIMARY_NBNS_SERVER_IP_ADDRESS (0x82)
#define IPCP_OPTION_SECONDARY_DNS_SERVER_IP_ADDRESS (0x83)
#define IPCP_OPTION_SECONDARY_NBNS_SERVER_IP_ADDRESS (0x84)

#endif
