/**
* UPF Event Exposure Service
* UPF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* SubscriptionsCollectionApiImpl.h
*
* 
*/

#ifndef SUBSCRIPTIONS_COLLECTION_API_IMPL_H_
#define SUBSCRIPTIONS_COLLECTION_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>

#include <SubscriptionsCollectionApi.h>


#include "CreateEventSubscription.h"
#include "CreatedEventSubscription.h"
#include "ProblemDetails.h"
#include "RedirectResponse.h"
#include <string>

namespace org::openapitools::server::api
{

using namespace org::openapitools::server::model;

class  SubscriptionsCollectionApiImpl : public org::openapitools::server::api::SubscriptionsCollectionApi {
public:
    explicit SubscriptionsCollectionApiImpl(const std::shared_ptr<Pistache::Rest::Router>& rtr);
    ~SubscriptionsCollectionApiImpl() override = default;

    void create_subscription(const CreateEventSubscription &createEventSubscription, Pistache::Http::ResponseWriter &response);

};

} // namespace org::openapitools::server::api



#endif
