/**
* UPF GET Private UE IP address Service
* Nupf_GetPrivateUEIPaddr Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.0.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "UEIPInfoGetApiImpl.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

UEIPInfoGetApiImpl::UEIPInfoGetApiImpl(const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : UEIPInfoGetApi(rtr)
{
}

void UEIPInfoGetApiImpl::search_ue_ip_info(const std::optional<Snssai> &snssai, const std::optional<std::string> &dnn, const std::optional<std::string> &ueIpv4Address, const std::optional<Ipv6Prefix> &ueIpv6Prefix, const std::optional<int32_t> &portNumber, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}
}
}
}

