/**
* UPF GET Private UE IP address Service
* Nupf_GetPrivateUEIPaddr Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.0.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* UEIPInfoGetApiImpl.h
*
* 
*/

#ifndef UEIP_INFO_GET_API_IMPL_H_
#define UEIP_INFO_GET_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>

#include <UEIPInfoGetApi.h>


#include "Ipv6Prefix.h"
#include "ProblemDetails.h"
#include "RedirectResponse.h"
#include "Snssai.h"
#include "UeIpInfo.h"
#include <string>

namespace org::openapitools::server::api
{

using namespace org::openapitools::server::model;

class  UEIPInfoGetApiImpl : public org::openapitools::server::api::UEIPInfoGetApi {
public:
    explicit UEIPInfoGetApiImpl(const std::shared_ptr<Pistache::Rest::Router>& rtr);
    ~UEIPInfoGetApiImpl() override = default;

    void search_ue_ip_info(const std::optional<Snssai> &snssai, const std::optional<std::string> &dnn, const std::optional<std::string> &ueIpv4Address, const std::optional<Ipv6Prefix> &ueIpv6Prefix, const std::optional<int32_t> &portNumber, Pistache::Http::ResponseWriter &response);

};

} // namespace org::openapitools::server::api



#endif
